### ISSUE TITLE
Redesigning next generation stompjs

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/stompjs#1]
As the history goes, the original JavaScript implementation of the STOMP protocol was maintained by Jeff Mesnil at https://github.com/jmesnil/stomp-websocket. He retired from the project few years back. The original code got forked by many as this library was used quite heavily.

A fork is getting maintained at https://github.com/stomp-js/stomp-websocket. Major work carried out:

- Auto reconnect
- Documentation revamp
- NodeJS support aligned to browser version (no hacks required)
- Minor upgrades to build and test infrastructure

In addition, a version specialized for Angular 2+ is getting maintained at https://github.com/stomp-js/ng2-stompjs which exposes nearly all STOMP features in RxJS/Angular way.

At this stage a rework in the original library is getting planned. Following is the current outline:

- CoffeeScript may no longer suit our needs, move to ES6 or TypeScript
- Keep the API as close to the current API with migration instructions for original version (https://github.com/jmesnil/stomp-websocket) and current version of (https://github.com/stomp-js/stomp-websocket)
- Pickup good things from any other forks. For example it seems there are some forks that can handle binary payloads.

Please add yourself or anyone else who would like to be part of this activity. 😃

**Comment by JimiC** [comment]
@kum-deepak Count me in if you decide to go with `Typescript`. The advantage is that the compiler can spit `ES6+` code and you will have auto-generated `types` declarations, reducing the labor of maintaining the `types` manually.

**Comment by kum-deepak** [comment]
Current plan is to create 3 distributions:

- A version that can be used a pure JS library
- A version that provides API using RxJS
- A version that is specific to Angular 2+

**Comment by kum-deepak** [comment]
@JimiC my current leaning is towards TypeScript as of now 👍

**Comment by JimiC** [comment]
Are we talking about an `All-In-One` approach or three separate projects?

**Comment by kum-deepak** [comment]
Currently open, it may be like third uses second and second uses first. Or, first and second share code and third uses second.

Do you think all-in-one might work?

**Comment by JimiC** [comment]
> Do you think all-in-one might work?

No.

> it may be like third uses second and second uses first.

More reasonable aproach.

**Comment by fpozzobon** [comment]
@kum-deepak good to me,
count on me as well :)

**Comment by jmls** [comment]
if possible, finer-grained error handling would be welcome - for example, I'd like to know that the username or password is incorrect, and therefore not to reconnect with the same details. 

Or having an invalid host .

At the moment, all I seem to get is a "whoops lost connection" with no indication why

**Comment by kum-deepak** [comment]
I have pushed initial version. It is almost direct conversion of the current code base. I have tried to configure build settings etc. All current test cases are passing in `node`, `firefox` and `chrome`. 😄 

Please have a look and propose if you will like to work on any specific features.

**Comment by aalbericio** [comment]
Hey Kum, 

These are really good news. I didn't see this topic until now but was thinking in requesting a total revamp of the library using TypeScript and RXJS. For me, and my team, this is definetely the way to go. 

Good to know the library is about getting a fresh and modern internals!

Congrats!

**Comment by kum-deepak** [comment]
@aalbericio once this library gets released I will be working on RxJS part.

There is currently https://github.com/stomp-js/ng2-stompjs - this is using RxJS, you can check the design and provide feedback.

**Comment by kum-deepak** [comment]
https://github.com/stomp-js/ng2-stompjs does not use anything Angular specific. So, it might even be usable outside Angular (I have never tried it though).

**Comment by kum-deepak** [comment]
Released 5.0.0 😄

**Comment by Anujmoglix** [comment]
seriously ? Package https://github.com/stomp-js/ng2-stompjs will work on react too ?

**Comment by Anujmoglix** [comment]
/@stomp/ng2-stompjs/bundles/stomp-ng2-stompjs.umd.js`: Module `@angular/core` does not exist in the Haste module map
