### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by Verikon** [stomp-js/stompjs#10]
I've forked this repo and can't get an initial build.

```
node_modules/@types/node/index.d.ts:6539:15 - error TS2720: Class 'Duplex' incorrectly implements class 'Writable'. Did you mean to extend 'Writable' and inherit its members as a subclass?
  Property 'pipe' is missing in type 'Duplex'.

6539         class Duplex extends Readable implements Writable {
```

Based upon this I assume there's a node version mismatch. What version of node has been targeted for this project? I've tried v8.12.0 (LTS) and v10.11.0 (current).

Am i overlooking something simple?

**Comment by kum-deepak** [comment]
Just checked:

- In my local machine I am running node v10.0.0 (on Mac OS X)
- At travis it uses v10.11.0 (see the log at https://travis-ci.org/stomp-js/stompjs) (on Ubuntu)

Please check https://github.com/stomp-js/stompjs/blob/master/.travis.yml for sequence of steps used at Travis. 

Which OS version you are using?

**Comment by Verikon** [comment]
Hi KD,

Using win10's WSL (ubuntu for windows) and your links compel me to believe it's certainly just me - I'll try again on a vanilla linux kernel.

Thanks for checking!
