### ISSUE TITLE
TypeError: Cannot read property 'publish' of undefined

### ISSUE THREAD

**Issue by dibyajyotiron** [stomp-js/stompjs#109]
while running my producer.js I get the following error ->
command : node stomjs/producer.js
response:
/home/dibyajyoti/Desktop/Feed/node_modules/@stomp/stompjs/bundles/stomp.umd.js:506
        this._stompHandler.publish(params);
                           ^

TypeError: Cannot read property 'publish' of  #undefined
    at Client../src/client.ts.Client.publish (/home/dibyajyoti/Desktop/Feed/node_modules/@stomp/stompjs/bundles/stomp.umd.js:506:28)
    at Object.<anonymous> (/home/dibyajyoti/Desktop/Feed/stomjs/producer.js:43:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad  #(internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

I'm using it with activemq, it's getting connected but throwing error while sending a message!
my stomp configuration is: 

`global.WebSocket = require("ws");

const Stomp = require("@stomp/stompjs");

if (typeof TextEncoder !== "function") {
  const TextEncodingPolyfill = require("util");
  TextEncoder = TextEncodingPolyfill.TextEncoder;
  TextDecoder = TextEncodingPolyfill.TextDecoder;
}

const stompConfig = {
  brokerURL: "ws://localhost:61614/ws",
  connectHeaders: {
    login: "username",
    passcode: "password"
  },
  debug: function(message) {
    console.log(message);
  },
  onWebSocketClose: function(message) {
    console.log("Reason: ", message.reason);
  },
  onWebSocketError: function() {
    console.log("Web socket error");
  },
  onConnect: function(frame) {
    console.log("Client connected to", frame.headers.server);
  },
  onDisconnect: function() {
    console.log("Client disconnected");
  },
  onStompError: function(frame) {
    console.log("Broker reported error: " + frame.headers["message"]);
    console.log("Additional details: " + frame.body);
  },
  reconnectDelay: 5000,
  heartbeatIncoming: 4000,
  heartbeatOutgoing: 4000
};

const client = new Stomp.Client(stompConfig);
client.activate();
client.publish({ destination: "/queue/test", headers: { priority: 9 }, body: "Hello, STOMP" });`

**Comment by kum-deepak** [comment]
There is a delay between calling `client.activate` and the actual connection getting established. You have two options:

- Write your code inside `onConnect`. However, `onConnect` gets called every time a connection is established (like a reconnect after an error).
- Check for [Client#connected](https://stomp-js.github.io/api-docs/latest/classes/Client.html#connected) before calling `publish`.

There is wrapper of this library - https://github.com/stomp-js/rx-stomp - that uses `rxjs`. That wrapper supports local queuing of messages if the underlying connection is not there.

**Comment by dibyajyotiron** [comment]
Cool, onConnect is working but while publishing, how do I check what message I'm publishing? using debug I get only ping pong but not the actual message that I'm publishing.
I want to log the message, where is it available?

`onConnect: function(frame) {
    if (client.connected) client.publish({ destination: "/topic/t1", body: "Bla Bla" });
    console.log("Client connected to", frame.headers.server);
    console.log(client);
  },`

**Comment by kum-deepak** [comment]
Please try setting https://stomp-js.github.io/api-docs/latest/classes/Client.html#logRawCommunication

**Comment by kum-deepak** [comment]
This can be set using config as well.

**Comment by dibyajyotiron** [comment]
Thanks for your help. Why is there no disconnected method? I wanted to configure to handle activemq failover and stopping message delivery in case of activemq failover.
maybe something like: 
if(client.disconnected) client.reconnect() 
so that the publisher doesn't post if my active mq stops responding.

**Comment by kum-deepak** [comment]
`reconnectDelay: 5000` in the configuration will trigger automatic reconnect in 5000ms. Please see https://stomp-js.github.io/guide/stompjs/2018/06/28/using-stompjs-v5.html#lifecycle-callbacks for different callbacks. In general this article is a good read.

**Comment by dibyajyotiron** [comment]
`reconnectDelay` only works if my activemq is not running and I start my producer, it'll tell me it's trying to reconnect. But let's assume a scenario where my activemq is running and producer is running and suddenly activemq is stopped. Now the problem is it's trying to reconnect but at the same time it's also publishing to the queue as well. 
I need to handle the fail over in a way that once the activemq is disconnected even though publisher is publishing, it should stop publishing and try to reconnect only.

**Comment by kum-deepak** [comment]
When the broker disconnects for any reason, https://stomp-js.github.io/api-docs/latest/classes/Client.html#onWebSocketClose will be called and https://stomp-js.github.io/api-docs/latest/classes/Client.html#connected will be set to `false`.

Depending on your application needs I can suggest one of the following:

- You can listen for  https://stomp-js.github.io/api-docs/latest/classes/Client.html#onWebSocketClose and pause/stop publishing. Listen for https://stomp-js.github.io/api-docs/latest/classes/Client.html#onConnect and resume/start publishing.
- Before attempting to publish check for https://stomp-js.github.io/api-docs/latest/classes/Client.html#connected and publish only if it is `true`.

**Comment by dibyajyotiron** [comment]
Thanks for the replies, for now I've switched to node-stomp and it's working fine for my usage. For my application requirement, stomp-js is not serving my purpose!
