### ISSUE TITLE
Reconnect only tries once

### ISSUE THREAD

**Issue by gokulakshay** [stomp-js/stompjs#130]
Set the reconnect to 5000 ms 

when my tomcat server stops, client tries to reconnect only once.

**Comment by kum-deepak** [comment]
Please provide the following information:

- Copy of the configuration
- Are you using SockJS?
- Enable debug and attach your entire console output (see https://stomp-js.github.io/faqs/2019/05/20/faqs.html#p-how-do-i-enable-logging-p)
