### ISSUE TITLE
I met 'TextEncoder' is not defined when I use connect function

### ISSUE THREAD

**Issue by TimbokY** [stomp-js/stompjs#146]
error: Unhandled promise rejection ReferenceError: 'TextEncoder' is not defined

Browser: `Microsoft Edge`

Edition: ^5.3.0

**Comment by kum-deepak** [comment]
Please check https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/06/29/pollyfils-for-stompjs-v5.html

**Comment by TimbokY** [comment]
> Please check https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/06/29/pollyfils-for-stompjs-v5.html

ok, I'm going to read！Thanks!
