### ISSUE TITLE
Due date for 5.0.0 or RC?

### ISSUE THREAD

**Issue by aalbericio** [stomp-js/stompjs#15]
Hello,

We're eager on adding this library into our production build but we don't want to add it while tagged as "beta".

The current milestone has no due date set so the question is: is there an estimate on when RC o final will be available?

Thanks in advance.

**Comment by kum-deepak** [comment]
I am targeting in few days, definitely by this weekend.

**Comment by kum-deepak** [comment]
Shifted #14 to post 5.0.0 and released 5.0.0.
