### ISSUE TITLE
Resubscribe destinations after connection lose

### ISSUE THREAD

**Issue by kosaa** [stomp-js/stompjs#161]
After first page visit there are two kind of messages CONNECT_ACK and SUBSCRIBE and its ok. There is connection to the server and subscribe to destinations.

But after web socket factory renew connection all subscribed destinations aren't resubscribed (only CONNECT_ACK is sent).

This is expected behaviour?

**Comment by kum-deepak** [comment]
I will suggest you go through https://stomp-js.github.io/guide/stompjs/2018/06/29/using-stompjs-v5.html and https://github.com/stomp-js/samples/

Exact answer to your query, you need to do all subscriptions in `onConnect` callback.

**Comment by 1001v** [comment]
@kum-deepak Hello. My question is a little offtop, but i'm not sure i should create a new issue. What if i need to do subscription in multiple places in my app? I can't add multiple connect event callbacks to stomp client because onConnect is a property. There's no such functional as addEventListener, on, off, once e.t.c. Thank you.

**Comment by kum-deepak** [comment]
Good that you asked. I faced the same issues. So, I created a wrapper to expose features as RxJS primitives - https://github.com/stomp-js/rx-stomp

So, https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#connected$ is an RxJS Observable that triggers whenever a (re) connection occurs. This can be subscribed to any number of times in different parts of your application.

This version also takes it further - on reconnection subscriptions are reestablished, if a message is sent when the underlying connection was not there it is sent upon a successful reconnection.

See https://github.com/stomp-js/samples/ for a few simple samples. There is a more complete sample using Angular where RxStomp is injected as dependency https://stomp-js.github.io/guide/ng2-stompjs/ng2-stomp-with-angular7.html. See more details at https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html.

Please raise issues if you need additional help.

**Comment by 1001v** [comment]
@kum-deepak thanks for your response. I actually came up with a similar solution, except i use vue. I just wanted to make sure that this solution was proper.
