### ISSUE TITLE
If server never replies to CONNECT frame, stompjs client connection hangs forever

### ISSUE THREAD

**Issue by VirtualDestructor777** [stomp-js/stompjs#165]
I had a macbook with Safari browser on WIFI talking to local server and what logs show is that stompjs opened web socket successfully, sent CONNECT frame and never got a reply.   On the server there is no record of receiving CONNECT frame.

In this scenario, as connection timeouts are kicked off upon receiving connect reply from server (as timeouts are figured based on client and server values), there is no timeout on connecting to the server and connection hangs.

This is based on the logs and reading stompjs source code.

This behavior is undesirable in a streaming application, however rare/edge-casey.

 Please let me know if I am missing something.   If not, I guess I could have timer with timeout making sure stompjs connection does not hang and kill it/try again if it does not call onConnect within a reasonable time; is there interest in adding this functionality to prevent hang ups on connect to the library?

Thanks!

**Comment by kum-deepak** [comment]
In current implementation if the underlying WebSocket connection fails to establish, it will try to reconnect. However, if there is no response for the CONNECT frame it will wait for ever.

You may handle this by starting a timer in `beforeConnect` and clearing it on `onConnect` and `onDisconnect`. In timer function you can call `deactivate` on the client. To attempt to connect again `activate` will need to be called.

**Comment by VirtualDestructor777** [comment]
Thank you for confirming and for workaround details.

Any plans to fix it?  :)

**Comment by bobohuochai** [comment]
It can be fix this problem  as @kum-deepak said.
` const { headers, reconnectDelay, connectTimeout, ...rest } = options;

    this.stompClient = new Client({
      brokerURL: connection,
      connectHeaders: headers ? headers : {},
      debug: function(str) {
        console.log(str);
      },
      reconnectDelay: reconnectDelay ? reconnectDelay : 1000,
      ...rest
    });

    // Fallback code
    // For SockJS you need to set a factory that creates a new SockJS instance
    // to be used for each (re)connect
    this.stompClient.webSocketFactory = function() {
      // Note that the URL is different from the WebSocket URL
      return new SockJS(connection);
    };

    let connectTimeoutHandler: any;

    this.stompClient.beforeConnect = () => {
      const self = this;
      // Callback, invoked on before a connection to the STOMP broker.
      connectTimeoutHandler = setTimeout(
        function() {
          console.log("stomp connect timeout:", new Date());
          (self.stompClient as Client).deactivate();
          clearTimeout(connectTimeoutHandler);
        },
        connectTimeout ? connectTimeout : 30 * 1000
      );
    };

    this.stompClient.onConnect = (frame: any) => {
      // Do something, all subscribes must be done is this callback
      // This is needed because this will be executed after a (re)connect
      this.logger.info("stomp Connected: " + frame);
      clearTimeout(connectTimeoutHandler);
      this.eventEmitter.ev_emit(EventTypeEnum.CONNECTED);
    };

    this.stompClient.onDisconnect = (frame: any) => {
      this.logger.info("stomp disconnected:" + frame);
      clearTimeout(connectTimeoutHandler);
    };
`

**Comment by kum-deepak** [comment]
New configuration option `connectionTimeout` is getting introduced.The client will retry to connect if the connection is not established before `connectionTimeout`. Logic is very similar to the comment above.

**Comment by kum-deepak** [comment]
It will be released as part of 6.x.

**Comment by kum-deepak** [comment]
Released as part of 6.0.0.
