### ISSUE TITLE
advice on async/await in message processing

### ISSUE THREAD

**Issue by abrin** [stomp-js/stompjs#170]
I am trying to implement an asynchronous function as part of my message processing (inside `subscribe()` I'm wondering if there are any good suggestions for doing this while ensure that only one message is accepted or processed at a time.  Are there any suggestions about the best approach for this?

* I can unsubscribe and re-subscribe between messages or deactivate and activate the client, but this feels like overkill (and it seems like with a little testing that unsubscribing before sending the ack() just leaves the message in the queue)
* in my queue, nack seems to reject the messages but they're gone into the ether

Is there a way to have the library wait for the next message somehow, or handle an asynchronous callback?

edit: I've tried following #59 and the advice on setting `prefetchSize` to 1 but it doesn't seem to be working for me.

**Comment by kum-deepak** [comment]
I am providing two alternates.

prefecth limits, ack, and nack are implemented by the broker. Actual support and behavior of these are specific to the broker. Which broker you are using?

First approach:

If you are using a broker like RabbitMQ or ActiveMQ you might be able to use suggestions from #59. If you are using Spring based broker - you may not be able to use this technique. Please note that the header is different for RabbitMQ (https://www.rabbitmq.com/stomp.html#pear.p).

Second approach:

See the schematic code (not tested), let me know if you need more assistance

```javascript

async function yourActualFunction (message) {
    // your processing
}

const queuedMessages = [];
let processingMsg = false;

function processQueuedMessages () {
    if (processingMsg) { // already processing a message
        return;
    }

    if (message.length === 0) { // no more messages to process
        return;
    }

    processingMsg = true;

    // Pick the oldest message, head of the queue
    const message = queuedMessages.shift();

    // Call your function that will process the message
    yourActualFunction(message).then(function () {
        // No longer processing a message
        processingMsg = false;

        // Try to process next, will not do anything if there are no more messages to be processed
        processQueuedMessages();
    });
}

stompClient.subscribe('/topic/chat', function (message) {
    // Add the message to the end of the queue
    queuedMessages.push(message);

    // Now try to process the queue, this function will not do anything if another message is in process
    processQueuedMessages()
});

```

**Comment by abrin** [comment]
Hi,
  Thanks so much for your thoughts and time.  I'm using the latest version of activeMQ (Artemis), but keeping it completely vanilla as we're going to be using AmazonMQ.  I also tried the solution in #59, but it didn't seem to have any effect.  I wonder if there's more that has to be configured in the broker to get this to work beyond the automatic generation of the `ANYCAST` queue.

Thinking through your solution, one of the challenges with it is that if the client dies with items in the queue, it will have consumed items that haven't been processed. 

Here's some of my code in progress, though, I'm not sure that's useful.

```
export function setupConsumer(client, queueName, callback) {

	// create a promise to resolve when we're connected
	let promise = new Promise(function(resolve, reject) {
		client.onConnect = function(frame) {
			// Do something, all subscribes must be done in this callback
			// This is needed because this will be executed after a (re)connect
			logger.info("connnected");
			connected = true;

			// if we're given a queue name and callback, set that up
			if (queueName && callback) {
				subscription = client.subscribe(
					prefix + queueName,
					function(message) {
						doWork(client, message, callback);
					},
					{ "subscription-type": queue_type, ack: "client-individual", 'activemq.prefetchSize':1 , 'consumer.prefetchSize':1}
				);
			}
			resolve(subscriptionId);
		};
	});
	client.activate();
	return promise;
}


export function doWork(client, message, callback) {
	// begin the transaction
	currentTransaction = client.begin();
	currentMessage = message;

	logger.debug(
		message.headers["message-id"],
		">> ",
		JSON.parse(message.body)
	);
	callback(message)
		.then(r => {
			finishWork();
                        message.ack({});
		})
		.catch(e => {
			error("error processing the queue", e, false);
			// add the message with exception to the failure queue
			addToQueue(client, prefix + "error", {
				message: message,
				error: e
			});
			// abort the transaction
			currentTransaction.abort();
		});
}

```

**Comment by kum-deepak** [comment]
If you are using manual ack, then until ack is called the message should not be marked processed by the broker. If the client dies with messages in the local queue, those should not get lost. We use RabbitMQ and we do rely on this behavior.

Converting onConnect to a promise is not straight forward. If you are setting up the client with auto reconnect, onConnect will be called for each successful connection. This makes Promises to be not suitable. In case you are interested please check https://github.com/stomp-js/rx-stomp.

Transactions in STOMP are not like Database transactions. Please see https://stomp-js.github.io/guide/stompjs/2018/06/29/using-stompjs-v5.html#transactions. You need to pass transaction id explicitly to ack calls.

In case you are using Node (which might be the case seeing your use case), consider switching to AMQP which allows far more control. There are some samples which show inter operating this library with AMQP/Ruby.

**Comment by kum-deepak** [comment]
If you are using manual ack, then until ack is called the message should not be marked processed by the broker. If the client dies with messages in the local queue, those should not get lost. We use RabbitMQ and we do rely on this behavior.

Converting onConnect to a promise is not straight forward. If you are setting up the client with auto reconnect, onConnect will be called for each successful connection. This makes Promises to be not suitable. In case you are interested please check https://github.com/stomp-js/rx-stomp.

Transactions in STOMP are not like Database transactions. Please see https://stomp-js.github.io/guide/stompjs/2018/06/29/using-stompjs-v5.html#transactions. You need to pass transaction id explicitly to ack calls.

In case you are using Node (which might be the case seeing your use case), consider switching to AMQP which allows far more control. There are some samples (https://github.com/stomp-js/samples/) which show inter operating this library with AMQP/Ruby.

**Comment by abrin** [comment]
I'll give those both a closer look. You're right that I'm new to this and am trying to apply a database-centric approach to the issues at hand.  The RxStomp on first look seems to do what I was trying to do with the promises (i.e. hide the logic of connection and subscription from my application. Also, you're right in guessing that I'm using NodeJS.  I have a ton of client-side code I'm trying to reuse if I can.

thanks again, I'll dig into these and see if I can't get it working. I really appreciate the patience and suggestions.

**Comment by abrin** [comment]
Hi,
  Just wanted tor report back:

1. I tried out RxStomp and while it looks nice, it doesn't seem to play nicely with nodeJs when using Webpack on first try because it assumes that `window` exists.  (note that window is being passed into the "require" on initialization: https://github.com/stomp-js/rx-stomp/blob/master/bundles/rx-stomp.umd.js  (I think changing "window" to "this" might solve it), and it might be tried by using : https://medium.com/@JakeXiao/window-is-undefined-in-umd-library-output-for-webpack4-858af1b881df. Should I create a ticket in that repo about it?


Separately, I did try modeling your methodology a bit more closely regarding the `ack` and it appears to be working quite nicely. Thank you!

**Comment by abrin** [comment]
Also, hopefully a useful note, but, Artemis doesn't seem to support the prefetch call, but older versions of ActiveMQ do.

**Comment by kum-deepak** [comment]
Release rx-stomp 0.3.4, with fix for webpack issue.

**Comment by abrin** [comment]
Thanks.  I was able to get rx-stomp working with this change. it is much cleaner.

```
import { RxStomp } from "@stomp/rx-stomp";
```

I also needed to build a promise based check around `client.activate()` to make sure the client was active before sending tasks or trying to process tasks off the queue. But, that was pretty easy.
