### ISSUE TITLE
Can't recive CONNECTED frame from rabbitmq by react-native on Android.

### ISSUE THREAD

**Issue by songxie** [stomp-js/stompjs#176]
Can't recive CONNECTED frame from rabbitmq by react-native on Android.But react-native on iOS is normally.

**Comment by kum-deepak** [comment]
This is caused by a bug in React Native. Please see details at https://stomp-js.github.io/workaround/stompjs/rx-stomp/ng2-stompjs/2019/06/10/react-native-null-chopping-issue.html

Try workaround 2 which should work with RabbitMQ and see if works for you.

**Comment by songxie** [comment]
Fixed.Thanks!
