### ISSUE TITLE
Missing Documentation on NPM?

### ISSUE THREAD

**Issue by Spiderpig86** [stomp-js/stompjs#184]
Just a quick heads up, seems that the documentation link for [Using StompJs v5](https://stomp-js.github.io/guide/stompjs/2018/06/28/using-stompjs-v5.html) is missing on the NPM page. Is this located in another location? The link was found [here](https://stomp-js.github.io/guide/stompjs/2018/06/29/using-stompjs-v5.html) instead. Thanks for the project. 😄

**Comment by kum-deepak** [comment]
Thanks for pointing out the error. I think I made a fundamental mistake in the Jekyll site by using date as part of the URL. Depending on when and where it gets processed, sometimes the URLs generated are off by one day.

The proper fix will be to remove date from the URLs and add appropriate redirects.

**Comment by kum-deepak** [comment]
Fixed :smile:. The URLs no longer have dates and redirects for older format are in place.
