### ISSUE TITLE
The heart-beat header is OPTIONAL

### ISSUE THREAD

**Issue by Kolahzary** [stomp-js/stompjs#188]
According to [STOMP specification](https://stomp.github.io/stomp-specification-1.2.html#Heart-beating):

> The heart-beat header is OPTIONAL. A missing heart-beat header MUST be treated the same way as a “heart-beat:0,0” header, that is: the party cannot send and does not want to receive heart-beats.

But currently stompjs throws an error if server doesn't send heart-beat header with CONNECTED frame:
`Uncaught TypeError: Cannot read property 'split' of undefined`

**Comment by kum-deepak** [comment]
Thanks for pointing out. It indeed should be as you have suggested. I will update the code and add test cases.

**Comment by kum-deepak** [comment]
See PR #189. Code change and new spec in https://github.com/stomp-js/stompjs/pull/189/commits/3e66d0b966f867f3af8b17de8bec351e529b58ae.

Heading for holiday, npm release likely on 31st December 2019.
