### ISSUE TITLE
undefined when importing

### ISSUE THREAD

**Issue by ramiel** [stomp-js/stompjs#19]
In version 5, in a frontend project compiled with babel/webpack

```
import StompJs from '@stomp/stompjs/esm5';
```

results in `undefined`. The same with esm6

**Comment by ramiel** [comment]
And `import StompJs from '@stomp/stompjs'` is not working

**Comment by kum-deepak** [comment]
There is no symbol called StompJs, Most probably you will need to import `Client`.

**Comment by kum-deepak** [comment]
Probably something like:

```javascript
import { Client } from '@stomp/stompjs';
```

**Comment by ramiel** [comment]
Is what I'm doing
```
import {Clilent} form '@stomp/stompjs/esm5';
```

but it's not very clear from the documentation or at least I could not understand it

**Comment by kum-deepak** [comment]
Please see https://github.com/kum-deepak/stomp-spring-react/blob/develop/src/App.js

I have updated it for #18

**Comment by kum-deepak** [comment]
Updating documentation and samples are on my list.

**Comment by kum-deepak** [comment]
Can I close this?

**Comment by ramiel** [comment]
Sure
