### ISSUE TITLE
Sockets leak in stomp.disconnect()

### ISSUE THREAD

**Issue by dviktorov** [stomp-js/stompjs#196]
Hello, 

We are using version 4.0.8 and creating Stomp clients over Sockjs. These Stomp clients are opened from a nodejs REST service that calls other services over Stomp/Websocket to process requests. Over time the service runs out of opened sockets and crashes. 

While checking this leak we found that stomp.disconnect() doesn't close the underneath Sockjs socket. When we overrode the disconnect() function and closed the socket ourselves, the issue seems to be resolved. Can you please suggest if its' the right approach or disconnect() is supposed to close the socket?

Attaching the code of how the disconnect() was overridden:

const SockJS = require("sockjs-client");
const Stomp = require("@stomp/stompjs");

getStompClient() = (stompUrl) => {
  const sock = new SockJS(stompUrl);
  sock.onclose = () => console.log("socket closed");
  const stompClient = Stomp.over(sock);
  const stompDisconnect = stompClient.disconnect;

  stompClient.disconnect = (callback, headers) => {
    console.log("disconnecting"); 
    stompDisconnect(callback, headers);
    **sock. close();**
  }

  return stompClient;
}

**Comment by kum-deepak** [comment]
Please try upgrading to the latest version. In v5 the library has been rewritten to avoid quite few similar issues. The lifecycle management has been updated quite a lot.

The syntax you are using is quite old - it will not support auto reconnect (which in your case you might not need).

Please see articles https://stomp-js.github.io/guide/stompjs/upgrading-stompjs.html and https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

Let me know if you are still facing the issue.

**Comment by dviktorov** [comment]
@kum-deepak Thank you for a quick response! We tried v5.4.3 and it's evidently a new level of convenience to use it. However, in the client creation we get the exact exception (this.configure is not a function) as described at https://github.com/stomp-js/stompjs/issues/95

Would there be an approach to resolve it?

**Comment by kum-deepak** [comment]
Please share a small project that demonstrates the issue.

**Comment by dviktorov** [comment]
Attaching the sample code using stompjs 5.4.3 and node 12.3.0. 

The thrown exception:
**Error: WebSockets error: indexSummary - this.configure is not a function**

const Stomp = require("@stomp/stompjs");
 
getStompClient = (stompUrl) => {

    const stompClient = Stomp.Client({
        brokerUrl: stompUrl,
        forceBinaryWSFrames: true,
        appendMissingNULLonIncoming: true,
        logRawCommunication: true,
        reconnectDelay: 0, // disable auto reconnect
        debug: str => {
            console.warn(str);
        }
    });

    return stompClient;
};

**Comment by dviktorov** [comment]
To follow up, the error was resolved by adding 'new' to the client creation:

const client = new StompJs.Client({....});
