### ISSUE TITLE
client.activate() generates an endless loop of opening a websocket then closing connection to undefined

### ISSUE THREAD

**Issue by NAlexP** [stomp-js/stompjs#198]
![image](https://user-images.githubusercontent.com/30490675/72985036-c3d0b580-3ded-11ea-8783-61b3022d4ab8.png)
![image](https://user-images.githubusercontent.com/30490675/72985067-d4812b80-3ded-11ea-9823-bb712b252ac5.png)
![image](https://user-images.githubusercontent.com/30490675/72985090-df3bc080-3ded-11ea-94fb-fbb7c6e92f7f.png)
There is no error thrown. 

The "_active" prop of my client object is set to true and "onStompError" is a [Function anonymous] when printing after activation. If I print the object before calling the activate(), "_active" is set to false and, what I believe to truly pose some interest: my "onStompError" prop is a [Function NoOp].

**Comment by kum-deepak** [comment]
The error you are seeing may be caused by variety of reasons including that the STOMP broker details are incorrect. Please start with one of the samples and see how it goes.

https://github.com/stomp-js/samples/
https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html
