### ISSUE TITLE
"message-id" and "ack" are switched incorrectly on STOMP v1.2/1.0

### ISSUE THREAD

**Issue by sh-developers** [stomp-js/stompjs#199]
In the code the intention of the version check in stomp-handler.ts#L196 is correctly done, however the headers are switched around. As defined in [STOMP 1.2 spec](https://stomp.github.io/stomp-specification-1.2.html#MESSAGE) you have to fetch the id to send with the ACK frame from the 'message-id', however this was switched around. If you reverse it, it works like intended:

https://github.com/stomp-js/stompjs/blob/71352a81dadbe29d6f61fcfa69a5ba93144baa2b/src/stomp-handler.ts#L196

**Comment by kum-deepak** [comment]
Thanks for the report. Let me investigate it. I will also add test cases to cover this feature.

**Comment by sh-developers** [comment]
Any progress?

**Comment by kum-deepak** [comment]
As per https://stomp.github.io/stomp-specification-1.2.html#ACK, it should use `ack` header from the message frame. In 1.1, it should use `message-id` and `subscription` headers from the message frame.

Am I reading the code or the STOMP specs incorrectly?

Which broker are you using?
