### ISSUE TITLE
Parser Errors

### ISSUE THREAD

**Issue by gkol** [stomp-js/stompjs#205]
I am still trying to diagnose the issue, but i have run into a few instances where the parser _bodyBytesRemaining will fall below 0 and it gives the appearance that STOMP has stopped working in our application. I can see the messages continue to process, but since the this._initState() was never called on receipt of a new message, the messages continue to fall on the floor. It appears that the new messages coming in are treated as the body of the previous message even though they contain their own headers and are complete messages. It is also intermittent and seems to happen randomly to the different connected clients even though they receive the same messages.

Has anyone else had this issue?

I was thinking of making the following modifications in my local resting to see if it helps with the issue. Changing the === 0 to <= 0 and putting a try/catch around the onFrame to ensure the next message will be processed if any exceptions happen to bubble up.

```
Parser.prototype._collectBodyFixedSize = function (byte) {
        // It is post decrement, so that we discard the trailing NULL octet
        if (this._bodyBytesRemaining-- <= 0) {
            this._retrievedBody();
            return;
        }
        this._consumeByte(byte);
    };
    Parser.prototype._retrievedBody = function () {
        this._results.binaryBody = this._consumeTokenAsRaw();
        try {
            this.onFrame(this._results);
        } catch (e) {
            console.error(e)
        }
        this._initState();
    };
```

**Comment by kum-deepak** [comment]
Seems interesting. Let me know how it goes.
