### ISSUE TITLE
How can I dynamically subscribe？

### ISSUE THREAD

**Issue by LeeHao92** [stomp-js/stompjs#217]
I know subscriptions should be done inside onConnect as those need to reinstated when the broker reconnects.

But sometimes I can't subscribe message in onConnect 😢.(eg: open another new subscription when user click button)

```js
<script>
const client = new Client()

client.onConnect(( ) => {
  client.subscribe('/a', (message: IMessage) => {
    console.log(message)
  })
})

client.activate()

$('.button').click(( ) => {
  // How should i subscribe message in onConnect ?
  client.subscribe('/b', (message: IMessage) => {
    console.log(message)
  })
})
</script>
```

**Comment by kum-deepak** [comment]
I faced similar issues and I could not figure out a non-messy solution. 

To solve this I have created a wrapper of this library called rx-stomp (https://github.com/stomp-js/rx-stomp). In this version you can subscribe anywhere (actually even before the underlying connection is established). Each subscription individually resubscribes at each reconnect. Also if you try to send a message when the underlying connection was missing it will send when the connection establishes. This library exposes stuff as RxJS primitives.

In our company we actually use rx-stomp or specialized version ng2-stompjs (which exposes rx-stomp classes as Angular services).

**Comment by LeeHao92** [comment]
thanks
