### ISSUE TITLE
Stomp.client is not a function

### ISSUE THREAD

**Issue by LakePeng** [stomp-js/stompjs#222]
Dear
I created one node application. The setp as below:
npm init
npm install @stomp/stompjs websocket --save
And the version is:
"@stomp/stompjs": "5.4.2",
    "websocket": "1.0.31"

I followed the instruction to create the client, but it show 'Stomp.client is not a function'
https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/Usage.md.html

The file name is ws-test.js and command is 'node ws-test.js'
The code as below:
`var Stomp = require('@stomp/stompjs');

var client = Stomp.client('ws://localhost:61614');

var headers = {
    login: 'mylogin',
    passcode: 'mypasscode',
    // additional header
    'client-id': 'my-client-id'
  };

var connect_callback = function() {
    console.log('connected');
};

var error_callback = function(error) {
  console.log(error.headers.message);
};

client.heartbeat.outgoing = 20000; // client will send heartbeats every 20000ms
client.heartbeat.incoming = 0;     // client does not want to receive heartbeats from the server
client.connect(headers, connect_callback,error_callback);`

**Comment by kum-deepak** [comment]
Wow, search engines can dig out old versions of documentation. The version of documentation that you have referred is valid till v4 of this library. For v5 please refer to https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html (there is a section for NodeJs).

The list of dependencies have changed as well, please see https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/pollyfils-for-stompjs-v5.html.

Please let know if it works for you, if not I will create a small sample.

**Comment by LakePeng** [comment]
It works. Thanks for your help! 
And it need install websocket and add the below line of code in the program.
`Object.assign(global, { WebSocket: require('websocket').w3cwebsocket });`
