### ISSUE TITLE
connectHeader is not passed to Spring server

### ISSUE THREAD

**Issue by arian-h** [stomp-js/stompjs#23]
Hello! 

I have the following code, using the stomp js client:

    this.client = new Client();
    this.client.configure({
      brokerURL: 'ws://localhost:8443/api/wsocket',
      connectHeaders: {
        login: "user",
        passcode: "password"
      },
      onConnect: () => {
        console.log('onConnect');

        this.client.subscribe('/ws/quote', message => {
          console.log(message);
          debugger;
        });
      },
      // Helps during debugging, remove in production
      debug: (str) => {
        console.log(new Date(), str);
      }
    });
    this.client.activate();

I was following your `stomp-spring-react` project on github. The problem is that I don't receive the header on the server side. I have a JWT Authentication Filter, that gets hit, but I don't get the header payload when I want to access it via: `request.getHeader`. I checked all the header names using `request.getHeaderNames` but I don't see it there either. Is this a bug or am I missing something here?

**Comment by kum-deepak** [comment]
I do not use Spring myself. Based on previous issues and Spring documentation I can suggest the following:

- WebSocket internally connects using HTTP(S). `request.getHeader` returns headers from the HTTP connection. WebSocket protocol does not allow setting custom headers for the HTTP connection.
- To get the headers from STOMP `CONNECT` frame you will need slightly different code. The best reference I have found is at: https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#websocket-stomp-authentication-token-based
- This example demonstrates Token authentication, however you can authenticate using headers you are sending. Your header will be accessible through `accessor` which is `MessageHeaderAccessor.getAccessor(message, StompHeaderAccessor.class)`.

I hope this helps.
