### ISSUE TITLE
Support for `consumerMaxRate` settings/Flow Control

### ISSUE THREAD

**Issue by montanapayne** [stomp-js/stompjs#245]
Dug through the documentation as much as possible and didn't find any mention of this optional setting for Flow Control as mentioned here: https://activemq.apache.org/components/artemis/documentation/latest/flow-control.html

We're using ActiveMQ over wss:// to read from queues. Wondering if there is any way to control the rate of message consumption via `consumerMaxRate` or something similar?

Thank you for your time!

**Comment by kum-deepak** [comment]
This library uses the STOMP interface of ActiveMQ. STOMP is a much simpler protocol in comparison to JMS or AMQP. ActiveMQ supports lesser features when accessed through STOMP. Please see https://activemq.apache.org/components/artemis/documentation/latest/stomp.html

If you are using this library on the server you might consider switching to AMQP which will allow more flexibility,

**Comment by montanapayne** [comment]
Thanks for the quick response! We ended up using prefetch setting to limit transmission rate and it's working well. 
```
            this.client.subscribe(
                this.config.activeTopic,
                this.onMessage.bind(this, this.config.activeTopic),
                {ack: 'client', 'activemq.prefetchSize': this.PREFETCH_SIZE}
            );

```
