### ISSUE TITLE
circular json on `CompatClient` or `heartbeat.client`

### ISSUE THREAD

**Issue by ilovett** [stomp-js/stompjs#265]
I have a project which uses stomp as external peer dependency and umd is being used.  There appears to be a circular dependency on `heartbeat.client` which refers to itself when attempting to `JSON.stringify` an object that it the stomp client is a part of.   I was able to workaround it by defining `toJSON` and just redacting it but just FYI.

**Comment by kum-deepak** [comment]
Many thanks for pointing it out. Since you are using CompatClient, I assume that you are on a reasonably recent version.

Will you be able to locate the offending code - either in the UMD bundle or the original source code.
