### ISSUE TITLE
Get 'ERR_CERT_COMMON_NAME_INVALID' in node.js

### ISSUE THREAD

**Issue by CocoHuang** [stomp-js/stompjs#271]
I'm running my code and getting an error of "error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID".
**### _i was wondering that is there some configration to disabled the ssl certificaition. (such as in the request module, i can set 'rejectUnauthorized: false' in req's header to disable the ssl certification) , it is very popular and useful in node.js_**

Here is my code:
```
import { Stomp } from '@stomp/stompjs';

let client = Stomp.client(`wss://url/ws`, [myToken]);
client.connect({}, rsp=> {
            console.log(rsp);
});
```

Log:
Opening Web Socket...
WebSocket connection to 'wss:url' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID
Connection closed to wss:url

Env:
"@stomp/stompjs": "^5.4.3"

thanks for your help.

**Comment by kum-deepak** [comment]
This indicates that the server certificate might be invalid. On the browser address bar put https://url/ws and check the error message.

**Comment by CocoHuang** [comment]
> This indicates that the server certificate might be invalid. On the browser address bar put https://url/ws and check the error message.

Thanks for reply. 
when i put my url in the browser, i'll get the same tips about certificate(net::ERR_CERT_COMMON_NAME_INVALID), but i can pass this error by click  "Advanced>Proceed to myUrl(unsafe)" in the browser.

in my develop situation, i run my code in visual studio code plugin webview env(which is like chrom ), i cannot click the button "Advanced", 
**_### so, i was wondering that is there some configration to disabled the ssl certificaition. (such as in the request module, i can set 'rejectUnauthorized: false' in req's header to disable the ssl certification)_** 

Here the official doc about rejectunauthorized(rejectUnauthorized <boolean>:If not false the server will reject any connection which is not authorized with the list of supplied CAs.):
https://nodejs.org/api/tls.html#tls_tls_createsecurepair_context_isserver_requestcert_rejectunauthorized_options

Thanks.

**Comment by kum-deepak** [comment]
This is a deliberate decision by browsers for security reasons. During WebSocket connections, there is no way to accept bad certificates. Please see https://stackoverflow.com/questions/5312311/secure-websockets-with-self-signed-certificate and https://security.stackexchange.com/questions/211618/bypassing-valid-certificate-requirement-for-websockets

You can try adding your root CA certificate to the Chrome (or Chromium) instance that VS Code is starting. If VS Code allows you to edit the command line for the browser you may pass additional arguments to ignore bad certificates.

Alternatively, if your setup allows connecting with ws:, you can switch to ws: for your development environment.

**Comment by CocoHuang** [comment]
Thanks for your reply.it works by using cerfitcation.
