### ISSUE TITLE
Is there any way to ignore the ERR_CERT_COMMON_NAME_INVALID with coding?

### ISSUE THREAD

**Issue by caozhaohong** [stomp-js/stompjs#273]
Please see FAQs at https://stomp-js.github.io/faqs/2019/05/20/faqs.html before reporting.
Dear kum-deepak:
   Thanks for ur professional support.

My question is base on:
https://github.com/stomp-js/stompjs/issues/271
https://github.com/stomp-js/stompjs/issues/272

According to ur clarification on issue 271, we already know how to do on Browser.

Now my scenario is, we are developing a client, the client is connecting `wss://url/ws`.

And we have no valid certificate. And our users is not plan to get and install valid certificate .

Then, we hope we can 'ignore the certificate ERR_CERT_COMMON_NAME_INVALID error and connect  `wss://url/ws`.

Is there any way to ignore the erro with coding way? For eg. set some connection attribute.

Thanks.

**Comment by caozhaohong** [comment]
Is there any coding attri like following example:

https://github.com/axios/axios/issues/284    ---example of axios 

const Agent = new https.Agent({
  rejectUnauthorized: false   //with this value equal to 'false', even the certificate is not set, client can still connect https url.
})

**Comment by kum-deepak** [comment]
I do not know of any way to programatically ignore this error.

**Comment by caozhaohong** [comment]
Thank u kum-deepak.

Is it possible that we raise a 'requirement' to add this 'ignore feature'?

**Comment by caozhaohong** [comment]
Thank u kum-deepak.

Is it possible that we raise a 'requirement' to add this 'ignore feature'?

**Comment by kum-deepak** [comment]
I do not think it is possible.

**Comment by caozhaohong** [comment]
Is it possible that we modify some source code and run with 'ignore error' (instead of raise requirement to stompjs community)?
And   we are willing to made it 'open-source' also.
     Can u give us any suggestion, for eg. we can modify which source file/which function. similar as:

axios/axios#284 ---example of axios
const Agent = new https.Agent({
 rejectUnauthorized: false  })

**Comment by caozhaohong** [comment]
If it is still 'impossible', why? Can u share us the 'reason'.

**Comment by kum-deepak** [comment]
Please check the links in https://github.com/stomp-js/stompjs/issues/271#issuecomment-686880273, these discuss why browsers do not allow this to happen.

The example you are qutoing https://github.com/axios/axios/issues/284 is nodejs, where it is possible to bypass.

**Comment by caozhaohong** [comment]
We are not browsers, we are a VSCode extension as a 'clinet role' to connect with a https servder. like :

Client ( VSCode extension, which used stoompjs, we are not browser) < ----------websocket---------------> HttpsServer;

**Comment by kum-deepak** [comment]
In that case, it might be possible by altering some code/configurations inside VSCode.
