### ISSUE TITLE
socket is not disconnected immediately on connection failure

### ISSUE THREAD

**Issue by bluestar39** [stomp-js/stompjs#298]
Hi,

I am using RxStompService in an angular 9 application and facing an issue where the socket is not disconnected immediately on connection failure but does so after 30-40 secs, below is my config which i use with rxStompService.configure - 

export const AppStompConfig: InjectableRxStompConfig = {
  // Which server?
  // brokerURL: this.appService.getEnvVariable('WS_HOST'),

  // Headers
  // Typical keys: login, passcode, host
  connectHeaders: {
    login: 'guest',
    passcode: 'guest',
  },

  // How often to heartbeat?
  // Interval in milliseconds, set to 0 to disable
  heartbeatIncoming: 1000, // Typical value 0 - disabled
  heartbeatOutgoing: 1000, // Typical value 20000 - every 20 seconds

  // Wait in milliseconds before attempting auto reconnect
  // Set to 0 to disable
  // Typical value 500 (500 milli seconds)
  reconnectDelay: 500,
};

How can I disconnect socket immediately on network failure? Thanks in advance!

**Comment by kum-deepak** [comment]
A new option has been added in the latest release. Please see https://stomp-js.github.io/guide/stompjs/rx-stomp/upgrading-to-stompjs-6-rx-stomp-1.html#discardwebsocketoncommfailure

You will need to update to the latest version to use this flag.
