### ISSUE TITLE
Unhandled received MESSAGE: MESSAGE when receiving message on subscribed client

### ISSUE THREAD

**Issue by owl-93** [stomp-js/stompjs#301]
I have a spring server that is sending out messages over a socket connection on certain server side events. In my web client, I have a SockJS connection that I am using with stompjs. I am able to connect to the server, subscribe to 3 different channels, verify the destination and the id of the channels, and receive a message.

However, when I receive a message, it doesn't appear to be routed to the appropriate handler registered in the stomp.subscribe("/topic/path/", handler) call.

In the browser logs, you can confirm that the destinations match and the subscription id's are correct, but I only ever get this message as if a subscription was not properly registered.

Below is a screenshot of the chrome console logs as well as a snippet of how I am subscribing to the socket topics
![Screen Shot 2020-11-13 at 5 24 26 PM](https://user-images.githubusercontent.com/7411331/99135004-18d7f500-25d5-11eb-8f0d-796ef610ff93.png)

```typescript
    let socket = new SockJS("http://localhost:8080/space")
    console.log(`init socket`);
    const stompClient = stomp.Stomp.over(socket)
    stompClient.connect({}, () => setSocketClient(stompClient), errorCallback)
```
Once I have obtained a successful connection, i then use that client to subscribe to a number of topics (spaces)

```typescript
let subscription = socketClient.subscribe(`/space/presence/${space.spaceId}`, (data) => console.log("received message on channel"), {id: space.spaceName})
```

Server code for what its worth looks something like this

```java
    @Autowired
    SimpMessagingTemplate messagingTemplate;
    //...
    messagingTemplate.convertAndSend("/space/presence/" + spaceId, updatedSpacePresence);
```

and spring socket configuration looks like 

```java
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/space")
                .setAllowedOrigins("*")
                .withSockJS();
    }
}
```

**Comment by kum-deepak** [comment]
I am not sure, though it appears that you are using quite an old version of the library. I will suggest the following:

Drop the last argument that explicitly sets the subscription id. The library should generate the id.

```javascript
let subscription = socketClient.subscribe(`/space/presence/${space.spaceId}`, (data) => console.log("received message on channel"), {id: space.spaceName})
```
to
```javascript
let subscription = socketClient.subscribe(`/space/presence/${space.spaceId}`, (data) => console.log("received message on channel"))
```

If it is a long term project, I will suggest to upgrade to latest verstion - https://stomp-js.github.io/#upgrading. In addition, since you are using SockJS, see https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

**Comment by owl-93** [comment]
@kum-deepak 
I have migrated stompjs to 6.0.0 and removed sockjs as it's not necessary. I can connect to the server, but now I'm having issues in the call to subscribe. Below is the relevant code and error message.

```typescript
import * as StompJS from '@stomp/stompjs'
//....
  const connectCallback = () => {
      setSocketClient(client)
      console.log("stomp connected to server")
      let subscription = client.subscribe("/presence/1", data => console.log(data))
  }

  const errorCallback = (e: any) => {
      console.log(`stomp error`)
      console.log(e)
      setError(e)
  }
  
  const disconnectCallback = () => console.log("stomp disconnect")

  const client = new StompJs.Client({
    brokerURL: `ws://localhost:8080/space`,
    onStompError: errorCallback,
    onConnect: connectCallback,
    onDisconnect: disconnectCallback
  })
  
  client.activate()
```

![Screen Shot 2020-11-16 at 8 54 26 AM](https://user-images.githubusercontent.com/7411331/99283321-b4da4a00-27e9-11eb-996c-d38a3b38040e.png)

**Comment by owl-93** [comment]
@kum-deepak 

Finally resolved the issue. The issue was being cause by the Recoil global state library for react. I believe it was creating immutable copies of the Client that was created, so subsequent calls to subscribe were unable to modify any of the instance vars for whatever reason.
