### ISSUE TITLE
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by khorn-infomedia** [stomp-js/stompjs#305]
We are getting this error when using the Client interface. Happens in latest Chrome, using native web sockets, after doing a deactivate then activate. 
We are cycling the client connections every 20-50 minutes, to reduce the impact of Thundering Herd, and to help load balance the sockets, across our 8 Web Sockets servers in cluster.

So when we do the activate , it seems STOMP is trying to send, but before the Web sockets has fully connected with server. This is common problem and when just using web sockets people watch the connection state, but for us this is buried within STOMP Client. Any help would be good. Note I removed our URLs from dump:

main.3f8bb3962ae7a7bd59b4.js:1 DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at e._transmit (https://..... /vendor.8ddae7b9819fccd670b1.js:1:3306686)
    at e.subscribe (https://..... /vendor.8ddae7b9819fccd670b1.js:1:3307802)
    at e.subscribe (https://.... /vendor.8ddae7b9819fccd670b1.js:1:3292273)
    at e.subscribe (https://.... /main.3f8bb3962ae7a7bd59b4.js:1:830788)
    at e.onWebsocketConnect (https://...../main.3f8bb3962ae7a7bd59b4.js:1:844682)
    at e.stompClient.onConnect (https://..../main.3f8bb3962ae7a7bd59b4.js:1:829797)

**Comment by kum-deepak** [comment]
We did face a similar issue earlier. This may be related.

First some hygiene - I am assuming that you are on the latest version of the library.

In the most recent release (October 2020), an important change has been made to `deactivate`, it is has been async. If you are going to call `activate` after deactivating you need to `await` for `deactivate`. Please see https://stomp-js.github.io/guide/stompjs/rx-stomp/upgrading-to-stompjs-6-rx-stomp-1.html#deactivate---async.

If the above does not help, please attach your configuration and the code portion you are using to deactivate/activate.

**Comment by khorn-infomedia** [comment]
Thanks for the reply. We were on 5.4.4. and now have upgraded to 6.0 and will see if we still get the issue. Yes we see deactivate is now async. So will update in a week or so.

**Comment by kum-deepak** [comment]
There is a possible race condition up to version 5.4 - if while calling the deactivate there was an active connection, immediately calling activate might have started a connection even before the previous one was fully closed. In version 6, the deactivate awaits till the currently active connection is properly disconnected.

Please keep me updated either way. Many thanks!

**Comment by khorn-infomedia** [comment]
We moved to Stomp V6, but now there is fundamental issues with the STOMP code and IE 11. Yes unfortunately we have clients using that for a few years still. The new code includes arrow functions, e.g.

**Comment by khorn-infomedia** [comment]
Maybe Babel can be used to remove the arrow function, so translate the whole STOMP.JS library ?Anyone tried that ?

**Comment by kum-deepak** [comment]
You are on the correct track, in my opinion, any of the following should work:

- Use Babel to cross-compile v6 to the desired version.
- In 5.4.4, wait for few seconds before calling `activate`.
- This library has been developed in TypeScript. You can clone v6, change the target in `tsconfig` and recompile. The target has recently been changed to `ES2015` from `ES5`. Instructions at https://github.com/stomp-js/stompjs/blob/develop/Contribute.md should help.

**Comment by kum-deepak** [comment]
One more possible option - depending on your situation might work. This library has a way to force disconnect a connection without doing a proper STOMP shutdown. This method is used quite a lot in the test setup.

See if instead of deactivate/activate you can issue a https://stomp-js.github.io/api-docs/latest/classes/Client.html#forceDisconnect, which will cause an auto reconnect.

**Comment by Dimanoid** [comment]
Just faced this issue on the latest 6.0.0 version. This not always but sometime happens after PC back from sleep and the page with the app still opened. Lib tries to reconnect but calls onConnect before real connect.
This is the callstack (code is minified so the line numbers are useless and removed)
```
DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at StompHandler._transmit 
    at StompHandler.subscribe 
    at Client.subscribe 
    at StompService.onConnect 
    at Client.onConnect 
    at StompHandler.onConnect 
    at CONNECTED 
    at Parser.onFrame 
    at Parser._retrievedBody 
    at Parser._collectBodyNullTerminated 
    at Parser.parseChunk 
    at WebSocket._webSocket.onmessage [as __zone_symbol__ON_PROPERTYmessage] 
    at WebSocket.wrapFn 
    at WebSocket.sentryWrapped 
    at ZoneDelegate.invokeTask 
    at Object.onInvokeTask 
    at ZoneDelegate.invokeTask 
    at Zone.runTask 
    at ZoneTask.invokeTask [as invoke] 
    at invokeTask 
    at WebSocket.globalZoneAwareCallback 
```

**Comment by kum-deepak** [comment]
Let me check. I will provide an update in a few days.

**Comment by kum-deepak** [comment]
Released @stomp/stompjs@6.1.0 and @stomp/rx-stomp@1.0.2. It sets https://stomp-js.github.io/api-docs/latest/classes/Client.html#connectionTimeout to 0 to de-activate this feature.

Please update and see if it fixes the issue.

**Comment by Dimanoid** [comment]
Just got same error on latest 6.1.0.

**Comment by kum-deepak** [comment]
Please send me the full console log and a copy of your configuration.

**Comment by Dimanoid** [comment]
All I had in console I posted earlier.
Config also has nothing special
            connectionTimeout: 5000,
            reconnectDelay: 10000,
            heartbeatIncoming: 20000,
            heartbeatOutgoing: 20000,
            + auth headers

**Comment by kum-deepak** [comment]
Please enable debug - https://stomp-js.github.io/faqs/faqs.html#p-how-do-i-enable-logging-p and attach the console output.
