### ISSUE TITLE
Getting "Invalid header" error when invoking `message.ack()`

### ISSUE THREAD

**Issue by CodeWithOz** [stomp-js/stompjs#308]
I get this error when I invoke `message.ack()`:
> Broker reported error: Invalid header
[some-file].js:78 Additional details: "ACK" must include a valid "id" header

Initially I was invoking `.ack()` with no arguments as shown in the [docs](https://stomp-js.github.io/api-docs/latest/classes/Client.html#ack), i.e. just simply `message.ack()`.

However after first noticing the error and seeing that those docs state that all 3 arguments are **not** optional, I changed to this:
```
const messageId = message.headers['message-id'] || undefined;
const subscriptionId = message.headers.subscription || undefined;
message.ack(messageId, subscriptionId, {});
```

I still got the error, so I switched to this:
```
const messageId = message.headers['message-id'] || undefined;
const subscriptionId = message.headers.subscription || undefined;
message.ack(messageId, subscriptionId, message.headers);
```

And I'm still getting the error. How can I fix this error? Thanks!

**Comment by kum-deepak** [comment]
ACK/NACK feature differs based on the underlying version of the STOMP protocol - 1.2 vs older. So, need the above details:

- Which broker are you using - please send me broker details including the version.
- Which version of this library are you using?
- Please attach a copy of the log message during the initial connection (that shows the STOMP version in use).
- Please attach the entire headers in the incoming message (it will help in checking if the broker is sending headers needed for ACK/NACK).

**Comment by CodeWithOz** [comment]
@kum-deepak thank you, see the details below:
- broker: RabbitMQ v3.8.0
- version of `stompjs`: 5.0.0
- log messages during initial connection:
> [08:07:51:0189]  INFO: TextrasStomp: >>> CONNECT
login:***
passcode:***
accept-version:1.0,1.1,1.2
heart-beat:10000,10000
[08:07:51:0474]  INFO: TextrasStomp: connected to server RabbitMQ/3.8.0

- `message.headers` object:
```
{
  content-length: "132"
  destination: "/exchange/***"
  message-id: "T_sub-0@@session-***"
  persistent: "1"
  redelivered: "false"
  subscription: "sub-0"
}
```

**Comment by kum-deepak** [comment]
Currently, I am using 3.7.3 on my local machine. Let me upgrade to the latest RabbitMQ and test. Please give me some time.

**Comment by kum-deepak** [comment]
I could notice one critical difference, your log output does not show an `ack` header in the message (below is a sample from my system with RabbitMQ 3.8.0):

```
{
    content-length:19
    ack:T_sub-0@@session-TjU8h1vFUcIq6w8APXdl2Q@@1
    redelivered:false
    message-id:T_sub-0@@session-TjU8h1vFUcIq6w8APXdl2Q@@1
    destination:/queue/test01
    subscription:sub-0
    content-length:19
}
```
Are you setting correct headers when subscribing? Please see https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html#acknowledgment. You need to set `{ ack: 'client' }` to use ack/nack.

**Comment by CodeWithOz** [comment]
Thanks! I needed to add `{ ack: 'client' }` when subscribing.
