### ISSUE TITLE
Module has no exported member 'over' and method 'connect' isn't recognized either

### ISSUE THREAD

**Issue by hadestructhor** [stomp-js/stompjs#313]
Hello,

This is my first time submitting an issue so sorry if i don't do it properly.

Basically, i've followed [this tutorial](https://dimitr.im/websockets-angular) and i installed the packages as it was asked of me.
I also tried downloading them with the command given on the website for it `npm i @stomp/stompjs`

And i keep getting these errors : 
![image](https://user-images.githubusercontent.com/60148800/103666887-80774480-4f75-11eb-801a-a1f73fd4fd8b.png)
![image](https://user-images.githubusercontent.com/60148800/103666960-9a188c00-4f75-11eb-8cdf-9c08bdb022e0.png)

The only similar issue i found was [this](https://stackoverflow.com/questions/39596304/module-sockjs-client-has-no-exported-member-sockjs) but it doesn't seem to work either.

Here's the content of my package.json file if the problem's comming from there: 
```
{
  "name": "transport-protocol-web",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.0.0-rc.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^9.0.0-rc.14",
    "@angular/compiler": "^9.0.0-rc.14",
    "@angular/core": "^9.0.0-rc.14",
    "@angular/forms": "^9.0.0-rc.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^9.0.0-rc.14",
    "@angular/platform-browser-dynamic": "^9.0.0-rc.14",
    "@angular/router": "^9.0.0-rc.14",
    "@azure/msal-angular": "^0.1.4",
    "@stomp/ng2-stompjs": "^7.2.0",
    "@stomp/stompjs": "^5.4.4",
    "@types/sockjs-client": "^1.5.0",
    "@types/stompjs": "^2.3.4",
    "angular-expressions": "^1.0.1",
    "azure": "^2.3.1-preview",
    "bootstrap": "^4.4.1",
    "docxtemplater": "^3.16.9",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "jszip": "^2.6.1",
    "jszip-utils": "^0.1.0",
    "msal": "^1.2.1",
    "popper.js": "^1.16.1",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "sockjs": "^0.3.19",
    "sockjs-client": "^1.5.0",
    "stream": "0.0.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.2",
    "@angular/cli": "^8.3.24",
    "@angular/compiler-cli": "^9.0.0-rc.14",
    "@angular/language-service": "^9.0.0-rc.14",
    "@types/jasmine": "^3.3.16",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.2",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.6.4"
  }
}

```

**Comment by kum-deepak** [comment]
I checked the tutorial at https://dimitr.im/websockets-angular. Based on the code it seems it refers to v3 of this library (current version 6).

The current version is written using TypeScript so using it is simpler than as outlined in that tutorial. In addition, there is a specialized wrapper of this library suitable for Angular. Please check https://stomp-js.github.io/#getting-started - follow the specific guides for Angular. You can also find a link to a sample Angular application on that page.

Please see if this helps.

**Comment by hadestructhor** [comment]
Thanks for the quick feedback, I've been trying to understand how to use stomp properly but can't seem to understand how it works properly.
The API i'm using doesn't have a ws url to the websocket and only has an http one.

For now i managed to connect via the websocket by doing this : 
```ts
import { Injectable } from '@angular/core';
import * as SockJS from 'sockjs-client';
import {WEBSOCKET_URL} from '../../api-url';
import { Client } from '@stomp/stompjs/esm5/client';
import * as StompJs from '@stomp/stompjs';

@Injectable({
  providedIn: 'root'
})
export class WebsocketService {

  private client: Client;

  constructor() { 
    this.client = new StompJs.Client();
    this.client = StompJs.Stomp.over(new SockJS(WEBSOCKET_URL));

    this.client.onConnect = function (frame) {
      console.log("websocket connected")
    };

    this.client.onStompError = function (frame) {
      console.log('Broker reported error: ' + frame.headers['message']);
      console.log('Additional details: ' + frame.body);
    };

    this.client.activate();
  }
}
```

I am very new to both angular and websockets so i tried looking online for what's best to do for what i want. 
I basically need to make a provider for hot observables that'll use the data recieved by the websocket. 

I think i need to follow [this](https://stomp-js.github.io/guide/ng2-stompjs/ng2-stomp-with-angular7.html#receiving-messages) guide but i can't see how to adapt it to use SocketJs instead. 

Do you know how i could make hot observables and a provider that gets the data received from the websocket ?

**Comment by kum-deepak** [comment]
There is mini guide around SockJS at https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

When you are following this [guide](https://stomp-js.github.io/guide/ng2-stompjs/ng2-stomp-with-angular7.html), you will need to provide [webSocketFactory](https://stomp-js.github.io/api-docs/latest/classes/Client.html#webSocketFactory) instead of [brokerURL](https://stomp-js.github.io/api-docs/latest/classes/Client.html#brokerURL) in your configuration.

**Comment by kum-deepak** [comment]
Your understanding regarding the `watch` call is correct, it creates a hot Observable that emits for each new message. `ng2-stompjs` takes care of automatic reconnetions and associated setup.

**Comment by hadestructhor** [comment]
Thanks a lot, i just followed the guides which are well explained and changed the brokerUrl in the config like you said for a webSocketFactory and everything worked like i wanted it to.

My configuration is like this if someone ever needs it : 
`ts
import { InjectableRxStompConfig } from '@stomp/ng2-stompjs';
import * as SockJS from 'sockjs-client';
import { WEBSOCKET_URL } from 'src/app/api-url';

export const RxStompConfig: InjectableRxStompConfig = {
  webSocketFactory : function () {
    return new SockJS(WEBSOCKET_URL);
  },

  heartbeatIncoming: 0,
  heartbeatOutgoing: 20000,
  reconnectDelay: 500
};
`
