### ISSUE TITLE
Request for clarification on PING opcode

### ISSUE THREAD

**Issue by nickshoe** [stomp-js/stompjs#317]
Should PING requests send 0x9 opcode instead of 0xA?

>  The Ping frame contains an opcode of 0x9.
>
> https://tools.ietf.org/html/rfc6455#section-5.5.2

The actual code is sending 0xA (LF) for PING frames.

https://github.com/stomp-js/stompjs/blob/507df2bc8d66d7a723c6da71fe5219c35c050ee4/src/stomp-handler.ts#L279-L284

https://github.com/stomp-js/stompjs/blob/507df2bc8d66d7a723c6da71fe5219c35c050ee4/src/byte.ts#L8-L10

Am I misinterpreting this?

I can work on the PR if this reasoning is correct.

**Comment by kum-deepak** [comment]
Never realized this. Did a bit of digging of my older notes and code samples. My current understanding:

[STOMP](https://stomp.github.io/stomp-specification-1.2.html) is occasionally used over WebSocket, however, it is designed to be used over any stream - typically TCP. This implementation assumes WebSockets, however, when used in NodeJS it is possible to use this library over regular TCP.

A ping in STOMP is not linked to WebSocket ping. A WebSocket ping is managed by the WebSocket layer, while the STOMP pings are managed by a higher layer.

This library aims to implement STOMP. In [heart-beating](https://stomp.github.io/stomp-specification-1.2.html#Heart-beating), it indicates EOL be used, which is later specified as `[CR] LF`.

Let us discuss and reach a conclusion.

**Comment by nickshoe** [comment]
It seems like I have confused WebSocket layer heartbeats (automatically handled by the browser and the "low-level" server?) with STOMP layer heartbeats (handled by the library and happening at the "application" layer).

The current implementation is therefore correct, as the official doc states:

> if the sender has no real STOMP frame to send, it MUST send an end-of-line (EOL)

So, thank you for the clarification.
