### ISSUE TITLE
connectHeaders does not add key to the GET request WebSocket handshake

### ISSUE THREAD

**Issue by kidfrom** [stomp-js/stompjs#322]
What I've tried:
1. I tried to use `connectHeaders` e.g
```
let stompClient = new StompJs.Client({
  connectHeaders: {
    mykey: "mykeyvalue"
  },
});
```

The expected result:
1. When I use Google Chrome's Developer Tools > Network > chat > Headers, I should see a "mykey" key with "mykeyvalue" as the value.

The actual result:
1. I did not find "mykey" key with "mykeyvalue" as the value in the Request Headers for the GET request to the "/chat" endpoint.

My goal is to add `Cookie` key to the Request Headers for React Native. The issue that React Native does not have Cookie, and `connectHeaders` does not add key to the GET request either.

I have created a Single Page Application with HTML + JS + Spring WebSocket + Spring Security to demonstrate a simple secured Chat App, [the repository](https://github.com/kidfrom/learn-java/tree/main/etc/spring-security-h2)

**Comment by kum-deepak** [comment]
Even though Websockets are internally HTTP, Web browsers in their Websocket implementations do not allow altering HTTP headers. The `connectHeaders` are used as part of the STOMP handshake (a CONNECT frame).

So, it is not possible to use Cookie-based authentication with Websockets. The following should help:

- Spring docs https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#websocket-stomp-authentication-token-based
- stompjs FAQ https://stomp-js.github.io/faqs/faqs.html#p-can-i-use-token-based-authentication-with-these-libraries-p

**Comment by kum-deepak** [comment]
A note to myself - this question comes quite often - add a FAQ entry.

**Comment by kidfrom** [comment]
@kum-deepak well noted. I will look for alternative without using Cookie.

About `cookie-based authentication`, could you please clarify? In my understading, `cookie-based authentication` is the `JSESSIONID` cookie. The Single Page Application I referenced use `cookie-based authentication` to `CONNECT` to the `/chat` WebSocket endpoint. In browser, the cookie is added to the request headers. I wish to replicate this in React Native if possible.

![image](https://user-images.githubusercontent.com/63768126/105695957-44f8e600-5f35-11eb-9ac9-482b8bf90ffa.png)

**Comment by kidfrom** [comment]
I got a harsh debate from the higher ups and we should stick with cookie-based authentication. PS: I have learnt that you can't add `Cookie` header, it's a forbidden header name. Reference: [Fetch Standard](https://fetch.spec.whatwg.org/#forbidden-header-name). This should not work:

reactnative.ts
```
fetch("localhost:8080", {
  method: "GET",
  headers: {
    cookie
  }
})
```

My goal is to use the current `cookie-based authentication` in React Native apps, I wrote the working example for Browser in [this repository](https://github.com/kidfrom/learn-java/tree/main/etc/spring-security-h2).

The issue is that `cookie` is somewhat a gray area in React Native. By gray area, I mean:
1. The endpoint that should have `Set-Cookie` header does not have `Set-Cookie` header if I hit the endpoint in React Native.
2. The React Native Fetch API does not send `Cookie` header (I can't test this, I need to solve issue no. 1 first). Some people recommends to use Axios.

@kum-deepak could you share some of your experience when integrating `stompjs/stomp-js` library with React Native or other mobile apps framework?

**Comment by kum-deepak** [comment]
In similar scenarios, we had used Token-based authentication. We do not use Spring, our brokers are usually RabbitMQ or ActiveMQ.

**Comment by kidfrom** [comment]
Hi, I solved the `Token-based authentication` with Spring Session.

[This is the changes I made](https://stackoverflow.com/questions/65972118/why-the-websocket-connection-is-not-terminated-after-the-session-is-timed-out)

The expected result is: The WebSocket connection should be terminated when the session expires. This is a default feature if we use the `Cookie-based authentication`.

However the actual result is: The WebSocket connection is not terminated when the session expires.

### When I use the `Cookie-based authentication`,

The WebSocket connection closed.
```
STOMP: Connection closed to ws://localhost:8080/chat
ChatListener.js:13 STOMP: STOMP: scheduling reconnection in 5000ms
```

This is the log I get from the Spring server.
```
2021-01-31 03:07:35.436 DEBUG 57252 --- [enerContainer-4] o.s.s.m.a.i.ChannelSecurityInterceptor   : Authorized GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={SPRING.SESSION.ID=c9fc3fe6-1ae9-4345-b107-c146edc0b2d6}, simpUser=UsernamePasswordAuthenticationToken [Principal=org.springframework.security.core.userdetails.User [Username=user, Password=[PROTECTED], Enabled=true, AccountNonExpired=true, credentialsNonExpired=true, AccountNonLocked=true, Granted Authorities=[]], Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[]], simpSessionId=556f1be7-0ee2-bc3b-b3eb-d08d493f2c32}] with attributes [authenticated]
```

@kum-deepak Currently I am investigating this. Please let me know if you have similar use case. Thank you.

**Comment by kum-deepak** [comment]
@kidfrom, sorry I do not use Spring. You may ask a query on StackOverflow.
