### ISSUE TITLE
onConnect-Callback

### ISSUE THREAD

**Issue by s-dschro** [stomp-js/stompjs#329]
Hey guys,

is it possible to wrap the `activate()` function in a Promise on your side?
Otherwise I guess this client is not that useful ... I am trying to use/execute it in a lambda function ...

My workaround atm is:

```
  async connect(): Promise<void> { // Todo!
    this.client.activate();
    while (!this.client.connected) {
      await new Promise(resolve => setTimeout(resolve, 50));
    }
  }
```

**Comment by kum-deepak** [comment]
There are variants of STOMP clients that expose onConnect as a Promise.

However, we need to be aware that this library supports automatic reconnection, so, onConnect will be called on each successful connection. This makes using promises not suitable.

There is a wrapper - https://github.com/stomp-js/rx-stomp - that exposes all the features as RxJS (https://rxjs.dev/guide/overview) primitives. In this version, you can write code outside onConnect. If you know RxJS or willing to learn it, this will probably give you what you are looking for.

**Comment by s-dschro** [comment]
Do you have any samples for this?

With this example I would run into the same issues:
https://github.com/stomp-js/samples/blob/master/rx-stomp/chat/rx-chat.html

**Comment by kum-deepak** [comment]
Not sure what you mean.

In this version, you simply subscribe or publish outside any onConnect type function - https://github.com/stomp-js/samples/blob/master/rx-stomp/chat/rx-chat.html#L84 or https://github.com/stomp-js/samples/blob/master/rx-stomp/chat/rx-chat.html#L114. Compare these with https://github.com/stomp-js/samples/blob/master/stompjs/chat/chat.html#L71 and https://github.com/stomp-js/samples/blob/master/stompjs/chat/chat.html#L110 (notice that you need to check if the client is connected before sending).

Internally, based on connection status, it will take care of the actual subscription (or re-subscription) and sending the messages.

For example, you can start a `watch` even before activating the client. The library will keep watching the connection status and do the subscription with the broker on each successful connection. You can test this behavior by restarting the broker.

To understand the working of this wrapper, it will be a good idea to run this sample and see the javascript console for the debug messages.

**Comment by kum-deepak** [comment]
Not sure what you mean.

In this version, you simply subscribe or publish outside any onConnect type function - https://github.com/stomp-js/samples/blob/master/rx-stomp/chat/rx-chat.html#L84 or https://github.com/stomp-js/samples/blob/master/rx-stomp/chat/rx-chat.html#L114. Compare these with https://github.com/stomp-js/samples/blob/master/stompjs/chat/chat.html#L71 and https://github.com/stomp-js/samples/blob/master/stompjs/chat/chat.html#L110 (notice that you need to check if the client is connected before sending).

Internally, based on connection status, it will take care of the actual subscription (or re-subscription) and sending the messages.

For example, you can start a `watch` even before activating the client. The library will keep watching the connection status and do the subscription with the broker on each successful connection. You can test this behavior by restarting the broker.

To understand the working of this wrapper, it will be a good idea to run this sample and see the javascript console for the debug messages.

**Comment by s-dschro** [comment]
When using this client within a lambda, I am seeing the following log:

```
2021-02-15T20:11:51.283Z	42a1aa39-efca-41ee-a866-00d94df67711	DEBUG >>> SEND
destination:test
content-length:3492
```

But there is no message in my queue `test`. It looks like the lambda already exists before the message is fully sent ... have you already seen such a behaviour?

**Comment by kum-deepak** [comment]
Sending a message is an asynchronous activity - the call itself will return before the message is sent fully. In the case of rxStomp, if a broker is not connected when a message is sent, the call will return immediately and the message will actually get sent when the broker connects next.

**Comment by s-dschro** [comment]
But why is it then a synchronous method, just returning a `void`? I would expect to get a Promise when sending a message, that can be awaited.

**Comment by kum-deepak** [comment]
This is an interesting idea. While designing this library I tried to make this (and a few other calls) async. However, ran into few issues:

- The underlying https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send call is asynchronous, however, does not return a Promise.
- There are differing interpretations of when one should consider a message to be sent:
  1. when it is written to the wire,
  1. when the broker has received it, or,
  1. when consumers have processed it.
- I am not aware if it can be achieved for case (i).
- For (ii), it is possible to return a Promise that resolves based on return receipt https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#watchForReceipt. The code sample can be used to create an async version.
- For (iii), there is no generic solution possible, however, in a few cases, with special conventions it can be achieved (see https://stomp-js.github.io/api-docs/latest/classes/RxStompRPC.html for one such case).

Let me know your views.

**Comment by s-dschro** [comment]
Maybe the lambda environment is a special use case ... which definitely needs a different programming model.
From my perspective: When using a method with a synchronous signature I am expecting that I can stop my process as soon as the method returns.
I would go for (ii), if this one is possible.

**Comment by kum-deepak** [comment]
For (ii), see the code example at https://stomp-js.github.io/api-docs/latest/classes/RxStomp.html#watchForReceipt, this should help you to wrap it to a Promise based call. Let me know if you need a code outline.

https://github.com/vitalets/websocket-as-promised does not convert the `.send` call to Promise based, which is needed for this case.

**Comment by s-dschro** [comment]
Regarding `websocket-as-promised` you are totally right. Maybe something like this:
https://houd1ni.github.io/WebsocketPromisify/

```
let receiptId = uuidv4();
rxStomp.watchForReceipt(receiptId, function() {
  // => I guess I would need to pass the lambda context object to this callback to stop the process here?
});
rxStomp.publish({destination: '/topic/special', headers: {receipt: receiptId}, body: msg});
```

**Comment by kum-deepak** [comment]
I think that should work.

Based on your requirements, you may be able to write similar code, though a different structure, without the RxJS wrapper.

**Comment by s-dschro** [comment]
So, this is my current solution:

```
  async send(
    queueName: string,
    body:      T,
  ): Promise<void> {
    try {
      await this.connect();
      const receiptId = nanoid();
      return new Promise((resolve, reject) => {
        this.stompjs.publish({ destination: queueName, body: JSON.stringify(body), headers: { receipt: receiptId } });
        this.stompjs.watchForReceipt(receiptId, () => {
          resolve();
        })
        // Todo: onError?
      });
    } catch(e) {
      console.error("RabbitMQ failed: %s", e);
      throw e;
    }
  }
```

Maybe this is helpful for others facing this issue.
