### ISSUE TITLE
Doesn't decode the exact message sent from server from 

### ISSUE THREAD

**Issue by bjdash** [stomp-js/stompjs#367]
There seems to be a bug where the parser doesn't decode the exact text sent from server. For example
Message sent by server: £
Message I get from stomp: �

Message sent by server: £123
Message I get from stomp: £12 (missing one character)

Message sent by server: €123
Message I get from stomp: €1 (missing 2 characters)

I did some digging and have have narrowed doen the bug to parser.js. On getting a message it first decodes the string to byte array
[parser.ts:90](https://github.com/stomp-js/stompjs/blob/61d721fec23e3f3891ac3a2fb857a8b4d41f2ba8/src/parser.ts#L90) `chunk = this._encoder.encode(segment); `

and then loops through each byte and tries to process the message
[parser.ts:105](https://github.com/stomp-js/stompjs/blob/61d721fec23e3f3891ac3a2fb857a8b4d41f2ba8/src/parser.ts#L105)
```
for (let i = 0; i < chunk.length; i++) {
   const byte = chunk[i];
   this._onByte(byte);
}
```

During this loop it reads the length from content-length header and sets up _bodyBytesRemaining
[parser.ts:195](https://github.com/stomp-js/stompjs/blob/61d721fec23e3f3891ac3a2fb857a8b4d41f2ba8/src/parser.ts#L195)
`this._bodyBytesRemaining = parseInt(contentLengthHeader[1], 10);`

And now the real issue, reading the contents until _bodyBytesRemaining === 0
[parser.ts:212](https://github.com/stomp-js/stompjs/blob/61d721fec23e3f3891ac3a2fb857a8b4d41f2ba8/src/parser.ts#L212)
```
if (this._bodyBytesRemaining-- === 0) {
    this._retrievedBody();
    return;
}
```

This is where the problem is. not every UTF-8 character returns a single byte when encoded via TextEncoder. For example £ return 2 bytes, € is 3 bytes.

so for message £123 the encoded bytes are [194, 163, 49, 50, 51] with a length of 5, but _bodyBytesRemaining is 4 since content-length for this message would be 4. And now because of the check `this._bodyBytesRemaining-- === 0` we miss out the last character. 

Same for €123. The encoded bytes are [226, 130, 172, 49, 50, 51] with length of 6 and _bodyBytesRemaining is 4. So we now miss out 2 characters.

_bodyBytesRemaining should not rely on content-length header as not all characters are single byte.

**Comment by kum-deepak** [comment]
Which broker are you using?

As per the standards, content-length is the number of octets (not chars) https://stomp.github.io/stomp-specification-1.2.html#Header_content-length

In case you are using a custom broker, set the content-length header to the number of octets (bytes). Alternatively, since your message is UTF text, skipping the content-length header should also work. In that case, it considers NULL to be the terminator.

**Comment by bjdash** [comment]
Thanks for clearing that up. Wasn't aware of the spec that content length is the octate count.
Could have saved some time by reading the spec first.
