### ISSUE TITLE
When the websocket reconnecting abnormally and reconnected sucessfully , but the connectCallBack is not triggered again!

### ISSUE THREAD

**Issue by chao-lv** [stomp-js/stompjs#381]
When the websocket reconnecting abnormally and reconnected sucessfully , but the connectCallBack is not triggered again!

How should i do ? (Based on stompjs & sockjs)

![](https://z3.ax1x.com/2021/09/05/hRmzvR.png)

**Comment by kum-deepak** [comment]
It seems you are using a version that is really old. The newer versions handle reconnects automatically and reliably. Please go to https://stomp-js.github.io/ and check the upgrading section.

For use with SockJS additionally, refer to https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

**Comment by kum-deepak** [comment]
If it is new project, please refer to the usage guiges from https://stomp-js.github.io/ - that is likely to give a more reliable solution.

**Comment by chao-lv** [comment]
> It seems you are using a version that is really old. The newer versions handle reconnects automatically and reliably. Please go to https://stomp-js.github.io/ and check the upgrading section.
> 
> For use with SockJS additionally, refer to https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

Now i use a newer version of stompjs & sockjs:

**Comment by chao-lv** [comment]
> It seems you are using a version that is really old. The newer versions handle reconnects automatically and reliably. Please go to https://stomp-js.github.io/ and check the upgrading section.
> 
> For use with SockJS additionally, refer to https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

(1) Now i use a newer version of stompjs & sockjs:
<script src="https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@stomp/stompjs@5.0.0/bundles/stomp.umd.js"></script>

(2)my client code:
![](https://z3.ax1x.com/2021/09/05/hWQTI0.png)

(3)And now, sometimes it’s good, sometimes it’s bad:
good:
![](https://z3.ax1x.com/2021/09/05/hWlVLd.png)

bad:
![](https://z3.ax1x.com/2021/09/05/hWlFzD.png)

(4) Now i don't know what to do, please give me some help, please...>_<

**Comment by kum-deepak** [comment]
For a week, I am in a very low connectivity area. So, help can be sketchy.

The convention for debug messages, >>> indicates a FRAME from the client to the broker. <<< indicates a frame from the broker to the client.

In this case, the server did not respond to the CONNECT frame - the connection is not getting established. In your first screen shot see the server response as a CONNECTED frame. Heartbeats start after a successful connection.

You are using v5, in that version there is no concept of a connect request timeout. The very latest version has an experimental flag https://stomp-js.github.io/guide/stompjs/rx-stomp/upgrading-to-stompjs-6-rx-stomp-1.html#connectiontimeout. See if it works for you.

I see that you are using RabbitMQ, which supports WebSockets out of the box. Please ask your backend developer to provide you the WebSocket endpoint details (it will start with ws:// or wss://). SockJS is unlikely to be as reliable as using WebSockets directly.

**Comment by chao-lv** [comment]
> > It seems you are using a version that is really old. The newer versions handle reconnects automatically and reliably. Please go to https://stomp-js.github.io/ and check the upgrading section.
> > For use with SockJS additionally, refer to https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html
> 
> (1) Now i use a newer version of stompjs & sockjs:
> https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js
> https://cdn.jsdelivr.net/npm/@stomp/stompjs@5.0.0/bundles/stomp.umd.js
> 
> (2)my client code:
> ![](https://camo.githubusercontent.com/fbbb2af1d357f48e97b480e5d191904d4600ab8b8aded09bff7cbc0ab66e1563/68747470733a2f2f7a332e617831782e636f6d2f323032312f30392f30352f6857515449302e706e67)
> 
> (3)And now, sometimes it’s good, sometimes it’s bad:
> good:
> ![](https://camo.githubusercontent.com/59419b040eda167f82cf74d88cea325c220c3afffacc641250964f9900aeb8ae/68747470733a2f2f7a332e617831782e636f6d2f323032312f30392f30352f68576c564c642e706e67)
> 
> bad:
> ![](https://camo.githubusercontent.com/b8bdcce48decd4e5c7babaed6b236d25fbf6032e2dc4b5daf8f6b6199908a7aa/68747470733a2f2f7a332e617831782e636f6d2f323032312f30392f30352f68576c467a442e706e67)
> 
> (4) Now i don't know what to do, please give me some help, please...>_<

Thanks for your helpfull proposal!
Update the versions to sockjs-1.5.2 & stompjs-6.1.2, then the problems above has gone!

**Comment by chao-lv** [comment]
> For a week, I am in a very low connectivity area. So, help can be sketchy.
> 
> The convention for debug messages, >>> indicates a FRAME from the client to the broker. <<< indicates a frame from the broker to the client.
> 
> In this case, the server did not respond to the CONNECT frame - the connection is not getting established. In your first screen shot see the server response as a CONNECTED frame. Heartbeats start after a successful connection.
> 
> You are using v5, in that version there is no concept of a connect request timeout. The very latest version has an experimental flag https://stomp-js.github.io/guide/stompjs/rx-stomp/upgrading-to-stompjs-6-rx-stomp-1.html#connectiontimeout. See if it works for you.
> 
> I see that you are using RabbitMQ, which supports WebSockets out of the box. Please ask your backend developer to provide you the WebSocket endpoint details (it will start with ws:// or wss://). SockJS is unlikely to be as reliable as using WebSockets directly.

Thanks for your helpfull proposal!
Update the versions to sockjs-1.5.2 & stompjs-6.1.2, the problems above has  all gone!
