### ISSUE TITLE
how do prevent connect two consumer to queue?

### ISSUE THREAD

**Issue by MohMehrnia** [stomp-js/stompjs#397]
how do prevent connecting two consumers to the queue?

**Comment by kum-deepak** [comment]
I am unable to understand your question, please elaborate. If possible add some code snippets.

**Comment by MohMehrnia** [comment]
I need to prevent connecting two clients to a queue (each queue can listen by one client)

**Comment by kum-deepak** [comment]
It is not specific to this client. However, brokers usually support this option. For example, RabbitMQ has a concept of `exclusive` queues that can only be subscribed by one client at a time. It also has a concept of anonymous, transient queues that are automatically destroyed when clients unsubscribe. You will need to check the broker documentation to check what the broker supports and what will fit your needs.
