### ISSUE TITLE
How correctly invoke `message.ack()`?

### ISSUE THREAD

**Issue by KnorienChang** [stomp-js/stompjs#398]
```javascript
// sockjs-client@1.5.2
// @stomp/stompjs@6.1.2
client.subscribe(
  destination,
  message => {
    message.ack() // or message.ack({ id: 'xxx' })
  },
  {ack: 'client'}
)
```
above, i got `undefined` with `id`

```
<<< MESSAGE
content-length:52
message-id:wnmbnafc-42
subscription:sub-0
content-type:application/json;charset=UTF-8
destination:/xxx
content-length:52

>>> ACK
id:undefined
subscription:sub-0
```

**Comment by kum-deepak** [comment]
The behavior is dependent on the STOMP version in use. Please attach the following details:

- Which broker are you using, including version.
- Log covering the initial connect sequence (CONNECT and CONNECTED) - STOMP version is mentioned here.

**Comment by KnorienChang** [comment]
> The behavior is dependent on the STOMP version in use. Please attach the following details:
> 
> * Which broker are you using, including version.
> * Log covering the initial connect sequence (CONNECT and CONNECTED) - STOMP version is mentioned here.


```
>>> CONNECT
accept-version:1.2
heart-beat:10000,10000

<<< CONNECTED
user-name:366639044945248256
heart-beat:0,0
version:1.2
content-length:0
```
![image](https://user-images.githubusercontent.com/22536347/140491624-56951123-5b2a-41c3-bc9c-56e4376b7b8c.png)

**Comment by kum-deepak** [comment]
This seems a bit peculiar. The connection is version 1.2. As per the version, it should have sent an `ack` header with the MESSAGE frame (see https://stomp.github.io/stomp-specification-1.2.html#ACK). Please check if your broker supports ack.

**Comment by KnorienChang** [comment]
maybe caused by backend？i will check later

**Comment by KnorienChang** [comment]
it work good for version 2.3.3, but failed in v5+。maybe transform/parse `message-id` failed？

**Comment by kum-deepak** [comment]
Version 2.3.3 did not support STOMP 1.2. The broker you are using is following STOMP 1.1 semantics for ack, while advertising to be 1.2. It works with 2.3.3 as it uses STOMP 1.1 in that case.

You can use 2.3.3 if it meets your need. Alternatively, you may try using the newer version in STOMP 1.1 mode (see https://stomp-js.github.io/api-docs/latest/classes/StompConfig.html#stompVersions).

**Comment by KnorienChang** [comment]
> Version 2.3.3 did not support STOMP 1.2. The broker you are using is following STOMP 1.1 semantics for ack, while advertising to be 1.2. It works with 2.3.3 as it uses STOMP 1.1 in that case.
> 
> You can use 2.3.3 if it meets your need. Alternatively, you may try using the newer version in STOMP 1.1 mode (see https://stomp-js.github.io/api-docs/latest/classes/StompConfig.html#stompVersions).

it works after i set stompVersions, thanks.
