### ISSUE TITLE
How to know that message was sent successfully?

### ISSUE THREAD

**Issue by akaNightmare** [stomp-js/stompjs#402]
Hello,

I'm wondering about a feature that can respond with some status about message sending to broker service?

Thanks in advance.

**Comment by kum-deepak** [comment]
If you are interested in ensuring that the broker received the message (not necessarily it was sent to/handled by a consumer), there is a STOMP concept called receipts. Please see https://stomp-js.github.io/api-docs/latest/classes/Client.html#watchForReceipt, it has examples that should be what you need.

**Comment by akaNightmare** [comment]
@kum-deepak another question, how to handle that the message wasn't sent?

**Comment by kum-deepak** [comment]
If the receipt is not received in a reasonable time (say 1000ms). You would need to use a timeout. If you are using the rx-stomp version of this library you can use an RxJS operator for that.
