### ISSUE TITLE
It it possible to use concurrency?

### ISSUE THREAD

**Issue by akaNightmare** [stomp-js/stompjs#406]
Hello,

I am wondering is it possible to use concurrency like https://github.com/amqp/rhea do ?

Thanks.

**Comment by kum-deepak** [comment]
Not sure what is your question, please elaborate, if possible with an example or schematic code.

**Comment by akaNightmare** [comment]
@kum-deepak Rhea lib has a credit window option 
```
credit_window - A 'prefetch' window controlling the flow of messages over this receiver. Defaults to 500 if not specified. A value of 0 can be used to turn of automatic flow control and manage it directly.
```
I assuming that something. similar is available in stompjs lib

**Comment by kum-deepak** [comment]
It is not a client-level feature. You need to check if your broker supports it over STOMP protocol. For example, RabbitMQ supports it over STOMP - https://www.rabbitmq.com/stomp.html#pear.p

Usually, brokers offer more functionality over AMQP in comparison to STOMP.
