### ISSUE TITLE
Backend recommendation with nodejs

### ISSUE THREAD

**Issue by acerola1** [stomp-js/stompjs#407]
I have a backend written in spring uses stomp over websocket. 
I want to create a simple substitute in my mock backend written in nodejs and express to test the stomp messaging.
I tried the express-ws library. It kind of work as I get a "Received data" debug message when I send a message from the server, but I could not get anything if I subscribe to a topic in stompjs.

Can you recommend a nodejs library for express to work with stompjs?

**Comment by kum-deepak** [comment]
I am not aware of any suitable alternatives. Please see https://github.com/stomp-js/stompjs/issues/382 as well.

**Comment by acerola1** [comment]
Thanks, I found stomp-broker-js and it works for me with stompjs. I was not able to configure to work from the same port as the express server, but it does not matter so much. It integrates well with my mock/developer nodejs server.
