### ISSUE TITLE
onConnect callback not called

### ISSUE THREAD

**Issue by numsu** [stomp-js/stompjs#408]
I have a React Native (with Typescript) application (https://github.com/numsu/nalli) and I'm currently developing a WebSocket integration for it to the backend.

I have an issue where the onConnect callback doesn't get called when the client connects. Here is the debug log:
```
2021-12-08T21:38:55.969Z Opening Web Socket...
2021-12-08T21:38:56.025Z Web Socket Opened...
2021-12-08T21:38:56.026Z >>> CONNECT
accept-version:1.0,1.1,1.2
heart-beat:10000,10000


2021-12-08T21:38:56.075Z Received data
2021-12-08T21:38:56.076Z <<< CONNECTED
version:1.2
heart-beat:0,0
```

My implementation is something of this sort at this time:
WsService
```
import { Client, StompSubscription } from "@stomp/stompjs";

export default class WsService {

    static subscribe = async (type: SubscriptionType, callback: (event: MyType) => void): Promise<void> => {
        const base = 'ws://my-endpoint';
        const headers = await this.getHeaders();
        this.client = new Client({
            brokerURL: `${base}/ws`,
            onConnect: () => {
                console.log('asd');
                this.subscription = this.client.subscribe(`/user/topic/${type}`, callback as any, headers);
                this.client.publish({
                    destination: `/app/${type}`,
                    headers: headers,
                });
            },
            debug: str => console.log(new Date(), str),
            logRawCommunication: true,
        });

        this.client.activate();
    }

}
```

That service gets called from elsewhere like this:
```
WsService.subscribe(SubscriptionType.NOTIFICATIONS, event => {
    ...
});
```

Using @stomp/stompjs version 6.1.2. TextEncoding polyfill is set.

**Comment by kum-deepak** [comment]
Please check this page https://stomp-js.github.io/workaround/stompjs/rx-stomp/ng2-stompjs/react-native-additional-notes.html

Kindly inform me if these do not resolve your issue.

**Comment by numsu** [comment]
Thanks. The appendMissingNULLonIncoming flag did fix this issue. Might I suggest that the documentation should be updated so it describes the symptoms of this issue rather than the root cause? It would have helped me to stumble upon the information.

**Comment by kum-deepak** [comment]
It will b great if you can raise a PR for the documentation. The documentation is hosted at https://github.com/stomp-js/stomp-js.github.io - (_posts and _faqs). Please let me know if you need more information.
