### ISSUE TITLE
Header disconnectHeaders not working

### ISSUE THREAD

**Issue by marcgise** [stomp-js/stompjs#411]
Hi,
I'm trying to set a disconnect headers object to the Stomp Client constructor, but when the client is disconnected, these headers are not sent to the server.
I don't know why it's happening, because connectHeaders are sent correctly, but disconnectHeaders are not working...
This is the code of how the client is built;

```
const user = 'my_user';
const stompClient = new Stomp.Client({
	brokerURL: stompUrl,
	connectHeaders: {
		user: user
	},
	disconnectHeaders: {
		user: user
	},
	...
});
stompClient.activate();
```

For disconnection, we're using following code:
```
stompClient.deactivate();
```

**Comment by kum-deepak** [comment]
Please enable logging and attach log output.

**Comment by marcgise** [comment]
How can I enable it? I set "logRawCommunication" to true, but I don't see anything in the console... Thanks

**Comment by kum-deepak** [comment]
Please see https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html#debug

**Comment by marcgise** [comment]
Finally it works ;) I don't know why the headers are not sent on closing the connection... :| Thanks!
