### ISSUE TITLE
How to handle message re-delivering? 

### ISSUE THREAD

**Issue by akaNightmare** [stomp-js/stompjs#413]
Hello,

I am wondering how to handle message re-delivering in a case when smth went wrong and the message should be reprocessed again?

https://activemq.apache.org/message-redelivery-and-dlq-handling

Thanks in advance.

**Comment by kum-deepak** [comment]
Not clear on your question. Most of the STOMP brokers (and this library) support transactions and acknowledgments. Do these not cover the case you have in mind?

**Comment by akaNightmare** [comment]
@kum-deepak I'm expecting when nack, this message should be redelivered after some time, but it's not. As I understand it should be handled by the client (stompjs).

Java client for STOMP doing that in exact way

**Comment by kum-deepak** [comment]
The test cases for this library are executed against RabbitMQ. There are a few scenarios related to ACK/NACK. Please see https://github.com/stomp-js/stompjs/blob/develop/spec/unit/ack.spec.js

These test cases use two clients. In the first test case, the message is NACKed 3 times and then ACKed on the 4th delivery.

The actual decision to redeliver is with the broker after a NACK.
