### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by or9** [stomp-js/stompjs#429]
I need documentation for `5.4.4`, and there doesn't seem to be any place to get it. Your documentation seems to be terribly lacking. In the codebase I'm working on, I see properties which are apparently undocumented anywhere, and yet your documentation claims "98% documentation coverage". If this was the case, I wouldn't have to look through the stompjs code to find what I'm looking for. The API docs URL (https://stomp-js.github.io/api-docs/latest/) seems to indicate some support for older/archive docs, so I've tried replacing `latest` with a tag, yet none of the tags I have tried work. 

You might say "Just upgrade to the latest version. It's not very difficult, and that way you'll have documentation." As it stands today, I would not recommend upgrading to the next version of this dependency for the codebase I'm working on because in a couple years, whoever ends up working on it won't be able to find documentation for that version either. It is of equal effort to remove it rather than passing the buck to the next person who has to deal with this.

**Comment by kum-deepak** [comment]
It is perfectly alright to use an older version of this library - there are critical applications using v2 of this library in production.

Documentation for older versions is not hosted by this project. You should download the source tarball from https://github.com/stomp-js/stompjs/tags and generate the documentation locally.

The source code has private, protected, and internal functions/properties. These should be avoided. Our advice would be to restrict your applications to using documented API - https://stomp-js.github.io/api-docs/latest/. If you want to use an undocumented API you would need to go through the source code.

You are more likely to get volunteer-based support if you are on one of the newer versions.
