### ISSUE TITLE
Can't connect to ther server using the latest version in React 

### ISSUE THREAD

**Issue by ThinhNguyenHoang** [stomp-js/stompjs#430]
My package json file is as follow: 
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@babel/core": "7.17.2",
    "@craco/craco": "^6.4.2",
    "@fortawesome/fontawesome-free": "^6.0.0",
    "@fortawesome/fontawesome-svg-core": "^1.3.0",
    "@fortawesome/free-brands-svg-icons": "^6.0.0",
    "@fortawesome/free-regular-svg-icons": "^6.0.0",
    "@fortawesome/free-solid-svg-icons": "^6.0.0",
    "@fortawesome/react-fontawesome": "^0.1.17",
    "@reduxjs/toolkit": "1.7.0",
    "@stomp/stompjs": "^6.1.2",
    "@types/node": "^17.0.10",
    "@types/react": "^17.0.20",
    "@types/react-dom": "^17.0.9",
    "@types/react-redux": "^7.1.22",
    "antd": "^4.18.0",
    "axios": "^0.24.0",
    "babel-plugin-import": "^1.13.3",
    "craco-less": "^2.0.0",
    "customize-cra": "^1.0.0-alpha.0",
    "dotenv": "^10.0.0",
    "firebase": "^9.6.7",
    "i18next": "^21.6.4",
    "i18next-browser-languagedetector": "^6.1.2",
    "image-to-base64": "^2.2.0",
    "lodash": "^4.17.21",
    "luxon": "^2.3.0",
    "normalizr": "^3.6.1",
    "query-string": "^7.1.0",
    "react": "^17.0.2",
    "react-dnd": "^14.0.5",
    "react-dnd-html5-backend": "^14.1.0",
    "react-dom": "^17.0.2",
    "react-highlight-words": "^0.17.0",
    "react-i18next": "^11.15.2",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.6",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "react-stomp": "^5.1.0",
    "recoil": "^0.5.2",
    "sass": "^1.47.0",
    "sockjs-client": "^1.5.2",
    "text-encoder": "^0.0.4",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0",
    "websocket": "^1.0.34"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "start-server": "json-server --watch ./fake_json_server/db.json --port 3001 --delay 2000",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "packageManager": "yarn@3.1.1",
  "devDependencies": {
    "@types/lodash": "^4.14.178",
    "@types/luxon": "^2.0.9",
    "file-loader": "^6.2.0",
    "uuid": "^8.3.2"
  }
}
```
My React Stomp Client is configured as follow: 
```
import React from 'react';
import {useAppDispatch} from "../../hooks/Redux/hooks";
import {socketAction} from "../../redux/features/SocketSlice/SocketHistorySlice";
import {Button} from "antd";
import {IMessage} from "@stomp/stompjs";


const Stomp = require("@stomp/stompjs");
export const client = new Stomp.Client();
client.configure({
        brokerURL: 'http://localhost:8080/lms',
        onConnect: () => {
            console.log('onConnect');

            client.subscribe('/topic/hello', (message: IMessage) => {
                console.log(`dash says: ${message}`);
                // dispatch(socketAction.addNewMessage(message.body));
            });

            client.subscribe('topic/hello', (message: IMessage) => {
                console.log("No dash says:" + message);
                // dispatch(socketAction.addNewMessage(message.body));
            });
        }
    },
);
console.log("CLIENT LOADED");
```

The console does print that "CLIEND_LOADED" but no 'onConnect' and when I try to publish a message, console show the error: 
![image](https://user-images.githubusercontent.com/60644156/155838821-7b26a309-8b1e-4726-a5e9-bae224f39030.png))

PS: The Spring server is properly configured (I managed to connect and publish to the server topic but I couldn't subscribe) so I changed to use this package but I could not connect to the server socket.

**Comment by ThinhNguyenHoang** [comment]
> Did you call `client.activate()`? This method should be called when the configuration is done and the connection should be attempted. Please see guides and samples - links at https://stomp-js.github.io/#getting-started

Thank you for your quick reply, I tried to call client.activate() as well but it is not connecting as well. 

I tried to find the docs for v6 but only find v5.

![image](https://user-images.githubusercontent.com/60644156/155845645-3babf75a-0dd9-4f52-9a1a-fb9b99d22f2b.png)

**Comment by kum-deepak** [comment]
All the documentation is valid for v6 as well. I will update the documentation to indicate the same.

Please check if your broker supports Websocket or SockJS as protocol (in Spring applications it is configurable). Even when it supports both, the URLs are likely to be different. Accordingly, you may need to check the https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

**Comment by ThinhNguyenHoang** [comment]
> All the documentation is valid for v6 as well. I will update the documentation to indicate the same.
> 
> Please check if your broker supports Websocket or SockJS as protocol (in Spring applications it is configurable). Even when it supports both, the URLs are likely to be different. Accordingly, you may need to check the https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

Thanks a lot, I managed to make it works. IMO, I really appreciate your effort on answering the issues and I admit most of the issues can actually be resolved by reading docs like you said. But, some of the docs are very misleading or ambiguous (Like you said, there are multiple way to do the same things but with different details of steps. And there are multiple sources of the docs not specifying the version as well, but the code do require the specific version to work though).
