### ISSUE TITLE
Can't resolve 'net' in stompjs\lib

### ISSUE THREAD

**Issue by LadyChatterleyLover** [stomp-js/stompjs#432]
version: 2.3.3

**Comment by kum-deepak** [comment]
Most probably you have raised the issue in the incorrect GitHub project. You are probably using https://github.com/jmesnil/stomp-websocket

In case you would like to migrate to [@stomp/stomps](https://github.com/stomp-js/stompjs)  please follow guides and migration instructions from https://stomp-js.github.io/
