### ISSUE TITLE
Connection disconnecting if one subscription fails

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stomp-js/stompjs#435]
I'm not sure if this is the way how RabbitMQ protocol works, but it seems that the client disconnects completely when I try to subscribe to two channels and one of them isn't existing.

Like following example:

1) connect to rabbitmq
2) subscribe to exchange/existing-channel-123 # fine
3) subscribe to exchange/non-existing-channel-123 # raises exception and disconnects client
4) client disconnects and reconnects

As far as I see it, it would be better if there is a new exception type / callback raised (like ```onSubscriptionFailed```) instead of killing the connection totally? Or am I wrong with my assumption?

Thank you!

**Comment by kum-deepak** [comment]
This is a situation that has annoyed me as well over the years.

- The STOMP protocol specifies, "The server MAY send ERROR frames if something goes wrong. In this case, it MUST then close the connection just after sending the ERROR frame." See: https://stomp.github.io/stomp-specification-1.2.html#ERROR
- RabbitMQ strictly follows the protocol by closing the connection after sending the ERROR frame.
- The connection is closed by the broker, so, no way to trap or handle it on the client.

The mitigation I have figured out is to carry out error-prone operations in a separate connection.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah I see, so it's related to the protocol not this package.. thanks for the useful insights! ❤️
