### ISSUE TITLE
Failed to construct 'WebSocket': The URL '[object Object]' is invalid

### ISSUE THREAD

**Issue by Rishikesh01** [stomp-js/stompjs#441]
I am getting "Failed to construct 'WebSocket': The URL '[object Object]' is invalid" error when I am using configuration of Client class

```
const stomp = new Client({
    webSocketFactory: () => {
      return new SockJS(data.url);
    },
    connectHeaders: {
      login: "test",
      passcode: "test",
      Authorization: "Basic dGVzdDp0ZXN0",
    },
    debug: function (str) {
      console.log(str);
    }
  });
  ```

**Comment by kum-deepak** [comment]
Please check which protocol your broker supports. SockJS and Websocket are different protocols. Typically a Webscoket URL will start with ws:// or wss://. The SockJS URLs will be http:// or https://

If you need additional instructions please check the guides linked from https://stomp-js.github.io/, if you use ScokJS check https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

There is a page for polyfills - it lists polyfills for different environments (including NodeJS): https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/pollyfils-for-stompjs-v5.html

I am closing the other issue #440 raised by you.

**Comment by Rishikesh01** [comment]
i am sending the correct url for Sockjs i.e http://

**Comment by Rishikesh01** [comment]
NVM i forgot * in ```import * as SockJs from "stomp-client"
