### ISSUE TITLE
/augment-websocket.ts has incorrect types

### ISSUE THREAD

**Issue by dmytro-kostiushko** [stomp-js/stompjs#445]
If you have a tsconfigration option "strictNullChecks" set to true - typescript will throw a compilation error stating that 
origOnClose is possibly null.

**tsconfig.json**
```

{
  "compilerOptions": {
    "target": "es5",
    "typeRoots": [
      "./types",
      "./node_modules/@types"
    ],
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "downlevelIteration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

TypeScript error in /Users/admin/IdeaProjects/processing-application-react-app/node_modules/@stomp/stompjs/src/augment-websocket.ts(32,5):
Object is possibly 'null'.  TS2531

    30 |     this.close();
    31 | 
  > 32 |     origOnClose.call(this, {
       |     ^
    33 |       code: 4001,
    34 |       reason: 'Heartbeat failure, discarding the socket',
    35 |       wasClean: false,

**Comment by kum-deepak** [comment]
Consider for v7.

**Comment by kum-deepak** [comment]
The next version is compiled with `strictNullChecks` set. See commit https://github.com/stomp-js/stompjs/commit/06ff8fca4199ec3669ef795e85284b9fcdcf1326.
