### ISSUE TITLE
How can I know the publishment is success or not?

### ISSUE THREAD

**Issue by hlf2016** [stomp-js/stompjs#446]
When I publish message to the rabbitmq , there is no any callback or callback value .

So I don't know whether the message was published successfully unless I debug in the debug function but it's inconvenient.

Is there any other way to get the result of publishment  of message?

**Comment by kum-deepak** [comment]
STOMP has a concept of receipts - RabbitMQ supports it. For any Frame sent to the broker, the client may request a receipt. Please see examples at https://stomp-js.github.io/api-docs/latest/classes/Client.html#watchForReceipt

**Comment by hlf2016** [comment]
Ok thx

**Comment by hlf2016** [comment]
> STOMP has a concept of receipts - RabbitMQ supports it. For any Frame sent to the broker, the client may request a receipt. Please see examples at https://stomp-js.github.io/api-docs/latest/classes/Client.html#watchForReceipt

Ok thx
