### ISSUE TITLE
Connection Name when connecting to RabbitMQ via Web STOMP

### ISSUE THREAD

**Issue by skazazes-work** [stomp-js/stompjs#449]
RabbitMQ Connections have an optional name parameter useful while debugging and triaging connections. Would it be possible to implement this parameter in the stomp library? 

In AMQP libraries this tends to be implemented as an argument to the connection constructor, it would be nice to have the same via STOMP if possible but this could be out of scope of this library

**Comment by kum-deepak** [comment]
Not sure if the RabbitMQ STOMP adaptor supports it. Please check https://www.rabbitmq.com/stomp.html to see the extensions and RabbitMQ-specific information.

**Comment by skazazes-work** [comment]
It does not appear that they are, thanks for the link.
