### ISSUE TITLE
Usage inside async function?

### ISSUE THREAD

**Issue by paul-uz** [stomp-js/stompjs#453]
Stompit seems to stop working when I use it inside of an async function.

With the function being called synchronously (removing any async calls inside of it) and the messages are sent without issue.

Is there a way to wrap the stompit send commands so they can be called inside an async function?

**Comment by kum-deepak** [comment]
Stompit is a different library, so, you need to raise issues in that project.

If you want to use this library (@stomp/stompjs) please check the documents at https://stomp-js.github.io/
