### ISSUE TITLE
Passing request headers when using SockJS

### ISSUE THREAD

**Issue by Rishabh12345678901** [stomp-js/stompjs#458]
```
const client = new StompJs.Client({
  connectHeaders: {
    "X-CSRF-TOKEN": token
  },
  debug: function (str) {
    console.log(str);
  },
  reconnectDelay: 5000,
  heartbeatIncoming: 4000,
  heartbeatOutgoing: 4000,
  webSocketFactory: ()=>(new SockJS("/ws"))
});

client.activate()

const subscription = client.subscribe(`/topic.${id}`, (res)=>{
	console.log(JSON.parse(res))
});
```

Using this config in the frontend, backend is expecting CSRF token in the request header. I think since I am using SockJS, the "X-CSRF-TOKEN" is not getting passed on handshake and I am getting a CSRF token mismatch error.
Is there a way to pass the CSRF token header when using SockJS ?

**Comment by kum-deepak** [comment]
You may not set or alter HTTP headers for the underlying WebSocket request - the browsers do not support it. Please see a longer answer in the FAQ https://stomp-js.github.io/faqs/faqs.html#p-can-i-use-token-based-authentication-with-these-libraries-p
