### ISSUE TITLE
@stomp\stompjs\src\client.js: Type 'Timeout' is not assignable to type 'number'

### ISSUE THREAD

**Issue by matanfil** [stomp-js/stompjs#466]
Hi,
New to using this lib. Went over every bit of documentation and couldn't find a solution to this error.
It appears client.js (line 425) is assigning setTimeout result to _connectionWatcher. This introduces ambiguity between the dom setTimeout and node setTimeout. I couldn't find any workaround via tsconfig or anything else.
Apparently fixing the code to global.setTimeout would set things right.

Any other suggestions on solving this issue in the meanwhile?

Thanks,
Matan.

**Comment by kum-deepak** [comment]
Please try the suggestion from https://stackoverflow.com/a/56239226/2565234 and see if it works, if it does, please submit a PR.

**Comment by kum-deepak** [comment]
Fixed in https://github.com/stomp-js/stompjs/commit/a6cfd415735323f56229e434554144bd4a659043
