### ISSUE TITLE
Does stompjs support streams?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stomp-js/stompjs#467]
As the title says, does stompjs support streams? https://rabbitmq.com/streams.html

Would be nice to add this info also to the Readme 👍

**Comment by kum-deepak** [comment]
Some users have reported having successfully used RabbitMQ streams. Please check https://www.rabbitmq.com/stomp.html#stream-support for details and steps.

Probably it can go in the FAQs.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm, I get following error: 

<img width="627" alt="Bildschirm­foto 2023-01-30 um 12 19 07" src="https://user-images.githubusercontent.com/10075/215463153-73c50021-cffd-4e61-8539-8feec90f559b.png">

Because stream queues are consumed my multiple clients and so auto-delete makes no sense (sorry if I get it wrong, I'm a rabbitmq newbie). Is there any way to disable auto-delete? Or tell stompjs to not create a new temporary queue, but use the stream queue?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm I still have problems to connect to a stream queue, since the subscribe method creates a temporary queue (which it shouldn't as far as I understand the rabbitmq streaming queues), but to bind directly to the streaming-queue?

Do you know an example somewhere?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Sorry that I wasted your time, I just had some queue settings false and it works now.. sorry & thanks for your answer!
