### ISSUE TITLE
advice on comparing message-id

### ISSUE THREAD

**Issue by berdiyev7** [stomp-js/stompjs#474]
Every time I query Rabbitmq, I add a unique uuid identifier to the message-id field, and I get a message with that identifier. Then I compare and try to write the message to setData, but at some point the messages don't compare  
 1. Is there any mechanism for comparing message-id messages?

**Comment by kum-deepak** [comment]
Your query is unclear to me. If your use case is doing an RPC (Remote Procedure Call), where there is a specific response for a request, you may consider using RPC support of rx-stomp - please check the guide https://stomp-js.github.io/guide/rx-stomp/ng2-stompjs/remote-procedure-call.html
