### ISSUE TITLE
Memory Overrun on unhandled exception

### ISSUE THREAD

**Issue by PutzWorks** [stomp-js/stompjs#481]
If the `this.onFrame` call inside `parser.js` causes an unhandled exception (due to poor developer code in the subscription function, like mine) this causes the `this._initState` function to not get called.  Then the next message received on the socket thinks that it's still part of the previous message.  This continues until the page crashes due to a memory overrun (the Page in Chrome displays "Aw Snap: Breakpoint").

If stomp-handler.js -> `serverFrameHandler` (or parser.js `this.onFrame`) was inside a try/catch block that would stop this problem from happening.  Since `serverFrameHandler` ends up being external to the stomp library it's definitely safest to catch any errors created by developers, like me...

Another option is to not allow the `_bodyBytesRemaining` to be negative.

**Comment by kum-deepak** [comment]
Thanks for pointing this out. This will be included in the next release.

**Comment by kum-deepak** [comment]
Fixed in the `develop` branch, to be released as part of v7
