### ISSUE TITLE
No heartbeat uploaded from WeChat applet

### ISSUE THREAD

**Issue by news00** [stomp-js/stompjs#483]
heartbeatIncoming: 5000,
heartbeatOutgoing: 5000,

**Comment by kum-deepak** [comment]
Please include your broker details, complete console log output, and your configuration.

**Comment by news00** [comment]
![image](https://user-images.githubusercontent.com/25659337/202590623-16d80bf1-dc1d-4dc7-b525-0979c4db0387.png)

**Comment by news00** [comment]
no upload heartbeat

**Comment by news00** [comment]
![image](https://user-images.githubusercontent.com/25659337/202590678-e553a780-d398-479c-b577-49feca5b9e9f.png)
