### ISSUE TITLE
Specify temporary queue name for subscription

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stomp-js/stompjs#516]
Hi,

I just wanted to ask if it is possible to specify the name for the temporary auto-delete queues, which are bound to the destination when I subscribe to a destination.

The reason is, that I would like to specify a fine graded JWT permission control, so I would like to give permission f.e. to "stomp-subscriptions-user123-abcde" and therefore I would like to call the temporary queue name not stomp-subscription-randomstring, but "stomp-subscriptions-user123-randomstring".

Is this possible?
Would be great if you could open the discussions on github, since I think this question is not really an issue but a discussion/question topic?

**Comment by kum-deepak** [comment]
Please use StackOverflow for these. Also, I think this question should be tagged to the broker you are using.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Sorry, i usw rabbitmq as my broker.

I only found that you can specify the subscription ID, but couldnt find anything related to the queue Name, so i thought I just ask here and provide a PR in case there is something which can be added to the documentation.

**Comment by h0jeZvgoxFepBQ2C** [comment]
So I guess you can't help me here @kum-deepak ?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Answered by the rabbitmq team: https://github.com/rabbitmq/rabbitmq-server/discussions/7230#discussioncomment-4925384
