### ISSUE TITLE
The incompatibility of Apple's NSURLSession WebSocket feature may cause the failure of receiving push notifications on iOS 15 or above systems.

### ISSUE THREAD

**Issue by mirror29** [stomp-js/stompjs#527]
In iOS 15 and above systems, the NSURLSession WebSocket feature is enabled by default, which may cause problems such as the inability to receive push notifications when using stompsjs. The option to enable/disable this feature can be found in Safari browser settings for testing purposes, but it cannot be turned off in a webview. What should I do?

**Comment by kum-deepak** [comment]
Does the issue relate to this library?

Please try StackOverflow, where your query is more likely to be answered.
