### ISSUE TITLE
Header x-stream-max-segment-size-bytes gets not transmitted during subscription

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stomp-js/stompjs#528]
I really try to get my head around following issue:

I have a queue named "public" which works fine in general. Now I tried to recreate it with the keyword ```x-stream-max-segment-size-bytes``` set, but it seems that this header doesn't get sent?

In my rabbitmq dashboard I can see that the queue has been created with this keyword:
![Bildschirm­foto 2023-02-22 um 10 42 47](https://user-images.githubusercontent.com/10075/220582346-cabd794a-9287-4904-8a97-96c8d20b1214.png)

But I get the error message that stompjs value was none?

![Bildschirm­foto 2023-02-22 um 10 40 41](https://user-images.githubusercontent.com/10075/220581794-abd53c86-1809-4b2a-a39f-f4f11125c4d2.png)

Header params:
![Bildschirm­foto 2023-02-22 um 10 43 23](https://user-images.githubusercontent.com/10075/220582511-202c0737-3891-4d9b-bab8-578af0418a06.png)

All other header params work well?
Any ideas?

Connecting via the ruby bunny gem works fine with ```x-stream-max-segment-size-bytes:1048576``` set.

**Comment by kum-deepak** [comment]
As per the log, the library is sending the header to the broker, so, the library may not be able to help much here.

Apologies no concrete help, just a few suggestions:

- Please check https://www.rabbitmq.com/stomp.html if not checked already.
- Occasionally, RabbitMQ does not support every features via STOMP than AMQP (which Ruby Bunny uses).
- Sometimes, at our company, we will create an exchnage or a queue using Bunny and then use it with STOMP. See, if that similifies the task for you.
- Ask as a question at StackOverflow. People with knowledge of RabbitMQ might be able to help.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thanks for your reply, 

we were using bunny + stompjs successfully already, it's just not working when I add the ```x-stream-max-segment-size-bytes``` declaration. Without it everything works fine on all sides.

So my best guess would be that the rabbitmq stomp or webstomp plugin filters this header..?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Looks like this was a bug and has been fixed: https://github.com/rabbitmq/rabbitmq-server/pull/7605
