### ISSUE TITLE
React Native - warn message sends Can't find variable: TextEncoder

### ISSUE THREAD

**Issue by omars94** [stomp-js/stompjs#53]
I am using Stompjs to connect with Apache ActiveMQ and Spring Server but when I run application I receive a console warning message and after I navigate to another Screen with lots of data I receive this error non-stop as if it went to a loop.

Error:
```
 [Unhandled promise rejection: ReferenceError: Can't find variable: TextEncoder]
- node_modules/@stomp/stompjs/bundles/stomp.umd.js:1538:30 in Parser
- node_modules/@stomp/stompjs/bundles/stomp.umd.js:1832:16 in start
- ... 13 more stack frames from framework internals
```

I believe this has to do with the package rather than my code
```
const stompConfig = {
    reconnectDelay: 100,
    heartbeatIncoming: 0,
    heartbeatOutgoing: 0,
    debug: function(str) {
      console.log(str);
    }
  }

  stompConfig.webSocketFactory = () => {
    return new SockJS(
        "http://192.168.1.2:8080/"
    );
  };
  client = new Client(stompConfig);

  client.onConnect = function(frame) {
    console.log('frame', frame.body);
  };

  client.onStompError = function(frame) {
    console.log('Broker reported error: ', frame.headers['message']);
    console.log('Additional details: ', frame.body);
  };

  client.activate();
```

**Comment by kum-deepak** [comment]
[TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) and [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) are needed by this library. Please see the following article for details on how to get poly-fills:

https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/06/28/pollyfils-for-stompjs-v5.html

**Comment by kum-deepak** [comment]
I am closing this, if it is still unresolved, please open a new issue.

**Comment by madsams** [comment]
@kum-deepak this article page is not found :'(

**Comment by kum-deepak** [comment]
Please try https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/06/29/pollyfils-for-stompjs-v5.html

**Comment by madsams** [comment]
@kum-deepak 
Thanx

**Comment by kum-deepak** [comment]
For react native, please also check https://stomp-js.github.io/workaround/stompjs/rx-stomp/ng2-stompjs/2019/06/10/react-native-null-chopping-issue.html

**Comment by madsams** [comment]
that doesn't work for me!!!

**Comment by madsams** [comment]
I tried nodejs solution in my react code
and it's worked!!!!!!! (I don't know why :D)
@kum-deepak
thanks

**Comment by engineforce** [comment]
Following works for me:

```sh
npm install text-encoding-polyfill
```

```js
// index.js
import 'text-encoding'
import Joi from '@hapi/joi'
```

**Comment by ufukomer** [comment]
@kum-deepak thanks for the link
@madsams thanks for telling where to focus :)

React Native already supports **WebSocket** thus we only need to add text-encoder to global **TextEncoder**, **TextDecoder** objects:

```js
const TextEncodingPolyfill = require('text-encoding');

Object.assign(global, {
  TextEncoder: TextEncodingPolyfill.TextEncoder,
  TextDecoder: TextEncodingPolyfill.TextDecoder,
});
```

**Comment by ArjunPatidar-numero** [comment]
@ufukomer @kum-deepak  I'm getting the same `Can't find variable: TextEncoder ` when adding the package `npm install jose `for key generation. How can I resolve my project is in react native expo.
@ufukomer Your answer is not clear to me.

**Comment by kum-deepak** [comment]
I do not use React Native myself. Please check https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/pollyfils-for-stompjs-v5.html#in-react-native which is based on information as reported by others.

**Comment by ArjunPatidar-numero** [comment]
@madsams Hey which solution you tried for `Can't find variable: TextEncoder` error can please tell me the process, It'll be helpfull.

**Comment by benodeveloper** [comment]
> ```js
> Object.assign(global, {
>   TextEncoder: TextEncodingPolyfill.TextEncoder,
>   TextDecoder: TextEncodingPolyfill.TextDecoder,
> });
> ```

this solved the problem, thank you 😁
