### ISSUE TITLE
Not connecting after updating Spring boot version

### ISSUE THREAD

**Issue by Globewyze1** [stomp-js/stompjs#551]
Previously, I was using the socket package stomp/stompjs with Spring Boot 2.3 and it was working properly. However, after updating Spring Boot to version 2.7.10, I am facing issues with the connection and there are no error messages being displayed.

**Comment by kum-deepak** [comment]
Please enable debug and attach your entire console output.

**Comment by jeanmelo25** [comment]
IDK if helps, but i think i'm facing the same problem!

[webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
styles.js:8000 
main.js:35 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
kendo-message.service.ts:156 Progress Kendo UI for Angular
base-paginated-grid.component.html:11 Progress Kendo UI for Angular
base-paginated-grid.component.html:34 Progress Kendo UI for Angular
index-esm.js:1 Progress Kendo UI for Angular
index-esm.js:1 Progress Kendo UI for Angular
index-esm.js:1 Progress Kendo UI for Angular
rx-stomp.config.util.ts:9 Mon Dec 04 2023 17:07:38 GMT-0300 (Hora padrão de Brasília) '"Opening Web Socket..."'
compat-client.js:32 Opening Web Socket...
client.js:285 WebSocket connection to 'ws://supply.local:4200/ws' failed: 
_createWebSocket @ client.js:285
(anonymous) @ client.js:218
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
invoke @ zone.js:372
onInvoke @ core.mjs:26274
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:26261
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
invokeTask @ zone.js:491
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2385
Show 17 more frames
Show less
rx-stomp.config.util.ts:9 Mon Dec 04 2023 17:11:38 GMT-0300 (Hora padrão de Brasília) '"Connection closed to ws://supply.local:4200/ws"'
rx-stomp.config.util.ts:9 Mon Dec 04 2023 17:11:38 GMT-0300 (Hora padrão de Brasília) '"STOMP: scheduling reconnection in 5000ms"'
stomp.js:45 WebSocket connection to 'ws://supply.local:4200/ws' failed: 
wsFn @ stomp.js:45
_createWebSocket @ client.js:282
(anonymous) @ client.js:218
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
invoke @ zone.js:372
onInvoke @ core.mjs:26274
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:26261
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
invokeTask @ zone.js:491
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2385
Show 18 more frames
Show less
compat-client.js:32 Connection closed to ws://supply.local:4200/ws
rx-stomp.config.util.ts:9 Mon Dec 04 2023 17:11:44 GMT-0300 (Hora padrão de Brasília) '"Opening Web Socket..."'

After a lot of time it crashes, but i think it is a timeout.
