### ISSUE TITLE
Module "net" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by JackieCheung** [stomp-js/stompjs#561]
Module "net" has been externalized for browser compatibility. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

**Comment by faganer** [comment]
me too

**Comment by kum-deepak** [comment]
Which version of the library are you using?

**Comment by tsurumure** [comment]
My version is 2.3.3

When i run build with PNPM, got a warning:
```
[plugin:vite:resolve] Module "net" has been externalized for browser compatibility, imported by "D:/CodeJava/QuickLaunchSpring/FrontendSys/node_modules/.pnpm/stompjs@2.3.3/node_modules/stompjs/lib/stomp-node.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```
So i was run `pnpm install net -D` to fix the warning.
