### ISSUE TITLE
Not able to subscribe to the topic seems to be onConnect function is not executing

### ISSUE THREAD

**Issue by tarunkhurana1988** [stomp-js/stompjs#578]
I am using NodeJS for backend and ReactJS for frontend using stomp protocol. I am using ws for websocket. I used the recent version of @stomp/stomjs and also tried with downgraded version. I am attaching files which is using 5.0.0.

The issue I am facing onConnect function not working.  Due to this I am unable to subscribe to topics. There are other functions like debug, beforeConnect working. 

It is not working in any browser not sure I am doing something wrong?

Can you please have a look?

[react-websocket.zip](https://github.com/stomp-js/stompjs/files/12209585/react-websocket.zip)

**Comment by kum-deepak** [comment]
Please switch on debug and attach your entire console output.

**Comment by tarunkhurana1988** [comment]
Hi @kum-deepak  attached the zip file and added a github repo also containing source code https://github.com/tarunkhurana/websocket-stomjs-demo

Also I am running the front-end application on different port and back-end application on different port. For that I have set the headers.
[output.zip](https://github.com/stomp-js/stompjs/files/12211293/output.zip)

**Comment by tarunkhurana1988** [comment]
@kum-deepak I tried to debug the code it seems to be server is not sending CONNECTED frame back to the client that's why the client onConnect callback is not executing but client is sending CONNECT frame based on the screenshot provided it seems to be server (stomp library) is not processing and sending the CONNECTED frame back and the server side is also not executing onConnect callback

**Comment by kum-deepak** [comment]
I am closing this issue, as it does not seem to be an issue related to this libraryl. Please reopen if there is a need.
