### ISSUE TITLE
one by one processing

### ISSUE THREAD

**Issue by IDIDIR** [stomp-js/stompjs#59]
When I work with queues, my subscriber receives records one by one, but the next element comes to me without waiting for the operation to complete with the previous one. I tried to add the ack in the expectation that the processing will become consistent, but this did not happen. in my code, everything is built on async/await, so I have to somehow configure the framework. what am I doing wrong?

**Comment by sare84** [comment]
Hello, 
I've had a similar problem and my solution was to add some more header information during the subscription process. My environment is an activemq server so the parameter here was 'activemq.prefetchSize': 1. 

The full call was:

`stompClient.subscribe('queuename', callback,  {'ack': 'client', 'activemq.prefetchSize': 1 });`

After adding this, the service got one message after another and not all at the same time.

Maybe this could help.

**Comment by kum-deepak** [comment]
Prefetch limit combined with manual ack will ensure messages one by one. RabbitMQ also supports prefetch count: https://www.rabbitmq.com/stomp.html#pear.p.

Having said that, most of the brokers do not guarantee messages arriving in order (almost always it will be in order, but no guarantees). Many times it is possible to structure the logic to handle messages in parallel and delivered out of sequence.

**Comment by IDIDIR** [comment]
It's work for my ActiveMQ
thx
