### ISSUE TITLE
subscribe Command, i  cann't get the callback

### ISSUE THREAD

**Issue by cristicmf** [stomp-js/stompjs#66]
subscribe Command, i  cann't get the callback
for example:
`
var topic="12345"
stompClient.subscribe(topic, function (message) {
            if (message.body) {
                console.log('stompClient.connected subscribe...');
                console.log("got message with body " + message.body)
            } else {
                console.log('stompClient.connected subscribe  ot empty message...');
                showGreeting("subscribe", topic, "");
            }
        }, {id: window.uuid, destination: topic});`

**Comment by kum-deepak** [comment]
Please enable debug and attach console output.

**Comment by cristicmf** [comment]
I can get the console output
but the callback function can not get work

**Comment by cristicmf** [comment]
"<<< SUBSCRIBE
version:1.1
content-length:6

"

**Comment by kum-deepak** [comment]
Please attach the entire console output.

**Comment by zhangya5847** [comment]
I have the same question.Could you tell me how do you do? Thx!

**Comment by kum-deepak** [comment]
Please enable debug and attach the entire console output.

**Comment by majastip123** [comment]
I have the same problem, how did you resolve?
