### ISSUE TITLE
How to subscribe non-durable queue?

### ISSUE THREAD

**Issue by BayesTech** [stomp-js/stompjs#70]
I am not sure if it is possible for angular 7 with stomjs to consume non-durable queue and exchange? Thanks

**Comment by kum-deepak** [comment]
This library does not assume whether a queue/exchange is durable. For exchanges/queues declared outside STOMP interface, brokers will have a mapping. For example mappings for RabbitMQ is available at https://www.rabbitmq.com/stomp.html#d

In additional notes you can look at https://github.com/stomp-js/ng2-stompjs - a wrapper that exposes operations as RxJS and supports Injectables.

**Comment by kum-deepak** [comment]
Closing this issue. Please let me know if it needs to be reopened. 😄
