### ISSUE TITLE
package not found ?

### ISSUE THREAD

**Issue by manuelc2209** [stomp-js/stompjs#79]
404 on lib. npm / yarn @stomp/stompjs, can someone test ?

**Comment by kum-deepak** [comment]
Just now tested with `npm -i`, works correctly.

**Comment by kum-deepak** [comment]
Can you please recheck?

**Comment by manuelc2209** [comment]
Rechecked, working now, idk, it was weird

A segunda, 4/03/2019, 09:28, Deepak Kumar <notifications@github.com>
escreveu:
