### ISSUE TITLE
How to install via NPM (TypeScript Node.js Project)

### ISSUE THREAD

**Issue by Fannon** [stomp-js/stompjs#8]
Hello,

thanks for creating this library! I'm very happy about the transition to TypeScript, btw.

Maybe I've overlooked something grand, but I didn't found the version 5 of stompjs on NPM. How would you install and use this with a TypeScript Node.js project?

Best,
Simon

**Comment by kum-deepak** [comment]
You did not overlooked anything 😄 

So far I have not released it to npm. I was working on the documentation, before I made an NPM release. I will release it as 5.0.0-beta later today.

**Comment by Fannon** [comment]
Ok :) No hurry, though!
