### ISSUE TITLE
Setting new connection params before re-connect

### ISSUE THREAD

**Issue by aalbericio** [stomp-js/stompjs#9]
Hello all,

We're currently sending a JWT as part of our connection string (we could use a header instead). This works as expected both in the client and in the server (authenticating the token).

Anyway, since those JWTs expire, we'd like a mechanism to update our connection string (or header) whenever the Client is in the **re-connection phase**. Right now, the reconnection is performed using the same (probably expired) token used at the very first connection attempt.

Is there any official approach to achieve that?

Could we use the "beforeConnect" hook to do that?

Thanks in advance.

**Comment by kum-deepak** [comment]
The current README points to 5.0.0-beta.x. This is a totally rewritten version, which overcomes many limitations of the version 4.x.x.

This version has quite few callbacks including `beforeConnect`. If you are currently using version 4.x.x, you will need to make some changes to your code. Please follow https://stomp-js.github.io/stompjs/additional-documentation/upgrading.html and https://stomp-js.github.io/stompjs/additional-documentation/usage.html

Please let me know if you are facing any issues.

May I request a favor - largest number of issues have actually been reported by  Spring users. After a bit of searching around i realized that there are few outadated/bad tutorials - ranked high by search engines. I have found that Spring documentation itself has correct suggestions.

I do not use Java/Spring myself. I will like to host a simple sample and HOWTO covering recommended way of usage.

**Comment by kum-deepak** [comment]
Can I close this issue?

**Comment by aalbericio** [comment]
Yes, sorry. 

After switching to version 5b, we are able to set new connection params at the **beforeConnect** hook.

Thanks
