### ISSUE TITLE
TypeError: this.configure is not a function when calling the Client constructor

### ISSUE THREAD

**Issue by ads-pedroleao** [stomp-js/stompjs#95]
Hi, I'm trying to implement StompJs in my React App, but when I call the constructor it gives me this TypeError:

> TypeError: this.configure is not a function
node_modules/@stomp/stompjs/bundles/stomp.umd.js:562

My implementation looks something like this:
`import * as StompJS from '@stomp/stompjs'`
`    const ws = StompJS.Client({`
`        brokerUrl: 'ws://...'`
`    });`

The weird thing is if I use the deprecated format it does run and connects to my websocket API. 

This implementation works:

`import * as StompJS from '@stomp/stompjs'`
`const ws = StompJS.Stomp.client(`ws://...`);`

I'm using v5.3.0-beta1 of StompJs

Is there something I'm missing here?

**Comment by kum-deepak** [comment]
I have released 5.3.0 today. Please try that. If you still face issues, please share a small application via GitHub. (I do not use React myself)

**Comment by kum-deepak** [comment]
Has your issue been resolved?

**Comment by ads-pedroleao** [comment]
Hey, as I had to deliver the feature I used a previous version, but I will try to update it. I'll close this issue and in case it doesn't work I reopen. Thanks.
