### ISSUE TITLE
How to subscribe to temporary queue

### ISSUE THREAD

**Issue by ramiel** [stomp-js/stompjs#99]
How the stomp documentation in rabbitMQ says, it's possible to send a message and specify a temporary queue valid per session. https://www.rabbitmq.com/stomp.html#d.tqd

The documentation also says that stomp automatically subscribes to that queue. How is possible to receive messages from that queue using this client? Where can be defined the callback for messages sent to that queue which should be subscribed?

**Comment by ramiel** [comment]
I tried to add to configuration

```
...
onUnhandledMessage: (message) => {
      console.log('I received this message from an auto subscribed queue', message);
}
```

but this callback is never called

**Comment by kum-deepak** [comment]
I do use this functionality in my projects. While sending a message, set `reply-to` header to `/temp-queue/replies`. On the other side retrieve the `reply-to` header and send the response back to that queue.

This client will receive the response in `onUnhandledMessage`.

A wrapper of this library (rx-stomp) uses this mechanism to implement RPC over STOMP (check out https://stomp-js.github.io/guide/rx-stomp/ng2-stompjs/2018/10/12/remote-procedure-call.html).

**Comment by ramiel** [comment]
I did something wrong on the worker and I was not really sending to the reply queue. My fault, sorry.
It works perfectly
